### ISSUE TITLE
InfluxLink wrong value sent

### ISSUE THREAD

**Issue by MiloshCZ** [domoticz/domoticz#1856]
Version: 3.8239, 3.8423
Domoticz sometimes sent wrong temperature value.

Wrong value at 02:27:36. Domoticz sent Barometer value as Temperature.
```
Sep 14 02:21:22 localhost domoticz[530]: 2017-09-14 02:21:22.600  InfluxLink: value Barometer,idx=6,name=Obývák value=1007.7
Sep 14 02:25:32 localhost domoticz[530]: 2017-09-14 02:25:32.015  InfluxLink: value Barometer,idx=6,name=Obývák value=1007.6
Sep 14 02:27:36 localhost domoticz[530]: 2017-09-14 02:27:36.699  InfluxLink: value Temperature,idx=6,name=Obývák value=1007.6
Sep 14 02:27:37 localhost domoticz[530]: 2017-09-14 02:27:37.270  InfluxLink: value Temperature,idx=6,name=Obývák value=15.6
Sep 14 02:31:46 localhost domoticz[530]: 2017-09-14 02:31:46.409  InfluxLink: value Barometer,idx=6,name=Obývák value=1007.5
Sep 14 02:32:49 localhost domoticz[530]: 2017-09-14 02:32:49.371  InfluxLink: value Barometer,idx=6,name=Obývák value=1007.6
```
Influx data:
```
2017-09-13T16:49:07.189933534Z	15.6
2017-09-14T00:27:36.715770059Z	1007.6
2017-09-14T00:27:37.278468073Z	15.6
```
There are more errors like this in log.
```
Sep 13 18:16:49 localhost domoticz[530]: 2017-09-13 18:16:49.936  InfluxLink: value Barometer,idx=6,name=Obývák value=1008.3
Sep 13 18:21:00 localhost domoticz[530]: 2017-09-13 18:21:00.006  InfluxLink: value Humidity,idx=6,name=Obývák value=58
Sep 13 18:23:04 localhost domoticz[530]: 2017-09-13 18:23:04.207  InfluxLink: value Barometer,idx=6,name=Obývák value=1008.2
Sep 13 18:30:22 localhost domoticz[530]: 2017-09-13 18:30:22.163  InfluxLink: value Barometer,idx=6,name=Obývák value=1008.3
Sep 13 18:47:01 localhost domoticz[530]: 2017-09-13 18:47:01.470  InfluxLink: value Barometer,idx=6,name=Obývák value=1008.2
Sep 13 18:49:07 localhost domoticz[530]: 2017-09-13 18:49:07.181  InfluxLink: value Temperature,idx=6,name=Obývák value=58
Sep 13 18:49:07 localhost domoticz[530]: 2017-09-13 18:49:07.181  InfluxLink: value Temperature,idx=6,name=Obývák value=1008.2
Sep 13 18:49:07 localhost domoticz[530]: 2017-09-13 18:49:07.181  InfluxLink: value Temperature,idx=6,name=Obývák value=15.6
Sep 13 19:07:51 localhost domoticz[530]: 2017-09-13 19:07:51.428  InfluxLink: value Barometer,idx=6,name=Obývák value=1008.1
Sep 13 19:09:56 localhost domoticz[530]: 2017-09-13 19:09:56.490  InfluxLink: value Barometer,idx=6,name=Obývák value=1008.2
```
Another strange log record:
`InfluxLink: value Temperature,idx=19,name=Elektroměr value=222571.000`
IDX 19 is virtual device for electricity consumption

I think, that it si problem with some race condition.

**Comment by gizmocuz** [comment]
Could you have a debug look on this ? Maybe add a mutex, or send the values one by one

**Comment by MiloshCZ** [comment]
I can create some testing enviroment. But i am not programmer.
Could you try to explain me what to do?

**Comment by gizmocuz** [comment]
Could you update to the latest beta version, as this might have already been fixed.
Because i am testing here at the moment with a temp+hum+baro sensor, and all goes OK

**Comment by MiloshCZ** [comment]
Thank you. I was update my system now. I will send you more info in couple days of testing.

**Comment by MiloshCZ** [comment]
No error for last 24 hours.

**Comment by gizmocuz** [comment]
Great ! Then i think it was already solved in the latest beta release

**Comment by MiloshCZ** [comment]
I have bad news. It looks that problem is back:
Time 22:41:03
```
Oct 29 22:36:05 localhost domoticz[16822]: 2017-10-29 22:36:05.190  InfluxLink: value Humidity,idx=12,name=Dětský-pokoj value=89
Oct 29 22:37:04 localhost domoticz[16822]: 2017-10-29 22:37:04.666  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.757
Oct 29 22:38:04 localhost domoticz[16822]: 2017-10-29 22:38:04.055  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
Oct 29 22:39:04 localhost domoticz[16822]: 2017-10-29 22:39:04.007  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
Oct 29 22:40:03 localhost domoticz[16822]: 2017-10-29 22:40:03.717  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
Oct 29 22:41:03 localhost domoticz[16822]: 2017-10-29 22:41:03.031  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
Oct 29 22:41:03 localhost domoticz[16822]: 2017-10-29 22:41:03.032  InfluxLink: value Temperature,idx=12,name=Dětský-pokoj value=89.0
Oct 29 22:42:02 localhost domoticz[16822]: 2017-10-29 22:42:02.387  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
Oct 29 22:42:02 localhost domoticz[16822]: 2017-10-29 22:42:02.927  InfluxLink: value Temperature,idx=12,name=Dětský-pokoj value=7.6
Oct 29 22:43:02 localhost domoticz[16822]: 2017-10-29 22:43:02.008  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
Oct 29 22:44:01 localhost domoticz[16822]: 2017-10-29 22:44:01.576  InfluxLink: value Voltage,idx=10,name=Dětský-pokoj-baterie value=3.779
```

Time 23:00:05 and 23:05:07
```
Oct 29 22:19:49 localhost domoticz[16822]: 2017-10-29 22:19:49.136  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:19:49 localhost domoticz[16822]: 2017-10-29 22:19:49.136  InfluxLink: value Humidity,idx=2,name=Gateway value=63
Oct 29 22:20:49 localhost domoticz[16822]: 2017-10-29 22:20:49.622  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 22:24:50 localhost domoticz[16822]: 2017-10-29 22:24:50.852  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:26:51 localhost domoticz[16822]: 2017-10-29 22:26:51.853  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 22:35:55 localhost domoticz[16822]: 2017-10-29 22:35:55.508  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:37:56 localhost domoticz[16822]: 2017-10-29 22:37:56.406  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 22:42:58 localhost domoticz[16822]: 2017-10-29 22:42:58.340  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:44:58 localhost domoticz[16822]: 2017-10-29 22:44:58.988  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 22:47:00 localhost domoticz[16822]: 2017-10-29 22:47:00.646  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:48:00 localhost domoticz[16822]: 2017-10-29 22:48:00.212  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 22:49:00 localhost domoticz[16822]: 2017-10-29 22:49:00.557  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:55:03 localhost domoticz[16822]: 2017-10-29 22:55:03.329  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 22:57:04 localhost domoticz[16822]: 2017-10-29 22:57:04.075  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 22:59:04 localhost domoticz[16822]: 2017-10-29 22:59:04.780  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 23:00:05 localhost domoticz[16822]: 2017-10-29 23:00:05.499  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 23:00:05 localhost domoticz[16822]: 2017-10-29 23:00:05.499  InfluxLink: value Temperature,idx=2,name=Gateway value=63.0
Oct 29 23:00:06 localhost domoticz[16822]: 2017-10-29 23:00:06.281  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 23:01:05 localhost domoticz[16822]: 2017-10-29 23:01:05.866  InfluxLink: value Temperature,idx=2,name=Gateway value=10.9
Oct 29 23:03:06 localhost domoticz[16822]: 2017-10-29 23:03:06.758  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 23:05:07 localhost domoticz[16822]: 2017-10-29 23:05:07.384  InfluxLink: value Temperature,idx=2,name=Gateway value=63.0
Oct 29 23:06:07 localhost domoticz[16822]: 2017-10-29 23:06:07.940  InfluxLink: value Temperature,idx=2,name=Gateway value=10.8
Oct 29 23:15:12 localhost domoticz[16822]: 2017-10-29 23:15:12.159  InfluxLink: value Humidity,idx=2,name=Gateway value=62
Oct 29 23:23:15 localhost domoticz[16822]: 2017-10-29 23:23:15.734  InfluxLink: value Temperature,idx=2,name=Gateway value=10.7
```

**Comment by MiloshCZ** [comment]
Another error:
```
Oct 30 19:50:00 localhost domoticz[16822]: 2017-10-30 19:50:00.145  InfluxLink: value Humidity,idx=6,name=Obývák value=71
Oct 30 19:57:16 localhost domoticz[16822]: 2017-10-30 19:57:16.602  InfluxLink: value Temperature,idx=6,name=Obývák value=8.5
Oct 30 20:06:38 localhost domoticz[16822]: 2017-10-30 20:06:38.191  InfluxLink: value Barometer,idx=6,name=Obývák value=1024.7
Oct 30 20:19:09 localhost domoticz[16822]: 2017-10-30 20:19:09.488  InfluxLink: value Barometer,idx=6,name=Obývák value=1024.8
.
.
.
Oct 31 06:47:41 localhost domoticz[16822]: 2017-10-31 06:47:41.048  InfluxLink: value Barometer,idx=6,name=Obývák value=1025.4
Oct 31 06:48:43 localhost domoticz[16822]: 2017-10-31 06:48:43.360  InfluxLink: value Barometer,idx=6,name=Obývák value=1025.3
Oct 31 06:48:44 localhost domoticz[16822]: 2017-10-31 06:48:44.195  InfluxLink: value Temperature,idx=6,name=Obývák value=71
Oct 31 06:48:44 localhost domoticz[16822]: 2017-10-31 06:48:44.195  InfluxLink: value Temperature,idx=6,name=Obývák value=1025.3
Oct 31 06:49:46 localhost domoticz[16822]: 2017-10-31 06:49:46.101  InfluxLink: value Temperature,idx=6,name=Obývák value=7.9
```
Humidity value from 19:50:00 written as temperature at 6:48:44 and barometer value from 6:48:43 written as temperature at 6:48:44.

Main problem is with combined sensors.

**Comment by gizmocuz** [comment]
Maybe we should add a mutex somewhere. Are you able to debug the code ? Its not that big

**Comment by MiloshCZ** [comment]
Sorry, but I am very bad programmer. I can write some simple code, but this is too complicated for me.
If you would want make PCB layout (high speed, DDR memories, USB, PCIe etc) I can help you, but with software....

**Comment by koenkooi** [comment]
I'm seeing the same issue, with latest 'development' with temp/hum sensors. See #1920 for the details of my setup.

**Comment by gizmocuz** [comment]
It is not related by a latest beta version koen... hope someone is willing to debug this...
maybe add a mutex ?

**Comment by koenkooi** [comment]
Would the mutex be in HttpPush.cpp, InfluxPush.cpp or somewhere else?

**Comment by gizmocuz** [comment]
Yes rust would be the question... And if it May be this issue
Maybe first add dinner jog lines what we put in the buffet and what hours out

**Comment by gizmocuz** [comment]
That would be the questions indeed... or if it solves the problem with the mutex.
You need to install visual studio, compile and set break points... 
without breakpoints and stepping through the code you won't solve this
also you need to add some log messages while debugging.. what do you put into the array, what is taken out of the array... things like that

**Comment by koenkooi** [comment]
I've switched all sensors to only send influx messaged on value change and that also triggers this bug. So the value swap happens before the comparison code.

**Comment by gizmocuz** [comment]
that is strange... i suspect other push systems would suffer from this too then ?

**Comment by xztraz** [comment]
Seem ok now when i updated myimperihome on the rpi. either its fixed or it just filters out weird data. :)

~~Not sure if related but data in imperihome connection looks weird too. not sure if domoticz or imperihome mucks up the data but graphs in domoticz look ok. Maybe completely unrelated.~~
![2017-11-21 21 53 53](https://user-images.githubusercontent.com/25690871/33096270-b3df6174-cf06-11e7-9430-b608670cd178.jpg)

**Comment by MiloshCZ** [comment]
Hi do you have any update about this problem? There is nobody else, who are using Influxdb?

**Comment by Masurov** [comment]
I am facing the same kind of problem.

**Setup**
- Temperature + Humidity device
- Datapush configured to send temperature on value change to influxDB

**Result**
**-100 values sometimes sent** to InfluxDB. Multiple times per day, no clear pattern.

**Raw data**

Domoticz value table on the timeframe

Time | Hum | Temp | comment
-- | -- | -- | --
2020-01-09 19:05:00 | 53 | 21.4 | 1st change
2020-01-09 19:10:00 | 53 | 21.4
2020-01-09 19:15:00 | 53 | 21.5 | 2nd change
2020-01-09 19:20:00 | 53 | 21.5
2020-01-09 19:25:00 | 53 | 21.5
2020-01-09 19:30:00 | 53 | 21.5
2020-01-09 19:35:00 | 53 | 21.5
2020-01-09 19:40:00 | 53 | 21.5
2020-01-09 19:45:00 | 53 | 21.5
2020-01-09 19:50:00 | 53 | 21.5
2020-01-09 19:55:00 | 53 | 21.5
2020-01-09 20:00:00 | 53 | 21.5
2020-01-09 20:05:00 | 53 | 21.5
2020-01-09 20:10:00 | 53 | 21.5
2020-01-09 20:15:00 | 53 | 21.5
2020-01-09 20:20:00 | 53 | 21.5
2020-01-09 20:25:00 | 53 | 21.5
2020-01-09 20:30:00 | 53 | 21.5
2020-01-09 20:35:00 | 53 | 21.5
2020-01-09 20:40:00 | 53 | 21.5
2020-01-09 20:45:00 | 53 | 21.5
2020-01-09 20:50:00 | 53 | 21.5
2020-01-09 20:55:00 | 53 | 21.6 | 3rd change

InfluxDb value table in the timeframe

Time | Temp | comment
-- | -- | --
2020-01-09 19:02:34 | 21.4 | 1st change
2020-01-09 19:12:12 | 21.5 | 2nd change
2020-01-09 20:50:04 | **-100** | **?!**
2020-01-09 20:50:15 | 21.6 | 3rd change

**Comment by ravsit-activum** [comment]
I have also this problem.
rpi3, domoticz 4.11414, influx 1.7.8 
(4.10717 have the same problem)

Device with idx=1 i Temp+Humi+Baro and push data to Distance table of influx

2020-01-29 05:46:40.593  InfluxLink: value Distance,idx=1,name=Katowice value=0.4
2020-01-29 05:46:40.593  InfluxLink: value Distance,idx=1,name=Katowice value=86
2020-01-29 05:46:40.593  InfluxLink: value Distance,idx=1,name=Katowice value=1002
2020-01-29 11:32:56.170  InfluxLink: value Distance,idx=1,name=Katowice value=3.0
2020-01-29 11:32:56.170  InfluxLink: value Distance,idx=1,name=Katowice value=75
2020-01-29 11:32:56.170  InfluxLink: value Distance,idx=1,name=Katowice value=1004
2020-02-05 21:26:53.935  InfluxLink: value Distance,idx=1,name=Katowice value=-1.5
2020-02-05 21:26:53.935  InfluxLink: value Distance,idx=1,name=Katowice value=77
2020-02-05 21:26:53.935  InfluxLink: value Distance,idx=1,name=Katowice value=1030
2020-02-13 09:05:54.056  InfluxLink: value Distance,idx=1,name=Katowice value=2.1
2020-02-13 09:05:54.057  InfluxLink: value Distance,idx=1,name=Katowice value=70
2020-02-13 09:05:54.057  InfluxLink: value Distance,idx=1,name=Katowice value=1019

I checked other tables and data - it turns out that there are more such incorrect entries with mixed types of devices


Very strange is that the problem occurs sporadically.
Something must be wrong in InfluxPush.cpp. 
I can do some reaserch/debug in free time.

**Comment by gizmocuz** [comment]
@ravsit-activum , that would be great !
Please have a look at 'ESP8266_Influxdb' 
https://github.com/hwwong/ESP_influxdb
I think it could be of great value to use this class

**Comment by ravsit-activum** [comment]
I solved the problem:

In the InfluxPush.cpp file
In the DoInfluxPush() function
line 144 should contain:

std::string vType = CBasePush::DropdownOptionsValue(**atoi(sd[0].c_str()**), delpos);

Until now, the variable m_DeviceRowIdx was passed there, which at the CInfluxPush::OnDeviceReceived event was set to a new idx (for a different sensor). Then the wrong device type was set.
The problem only appeared when many sensors transmit data more frequently. I got repetitive errors when I transferred data with a frequency of 1 / sec. At a lower frequency it also happened, but rarely.
In specific conditions, the time dependencies between the handling of queued data and the event of new data being received caused this error.
Greetings to All.

**Comment by gizmocuz** [comment]
@ravsit-activum , thanks for spotting !

Could you also test with:

std::string vType = CBasePush::DropdownOptionsValue(atoi(std::stoi(sd[0]), delpos);

If that works, would you like to make a PR or do you want me to change this ?

**Comment by ravsit-activum** [comment]
It works, but:

std::string vType = CBasePush::DropdownOptionsValue(**std::stoi(sd[0])**, delpos);

Do this change, please.
And if is it possible with issue #3960.

**Comment by gizmocuz** [comment]
Thanks, what do you mean with "Do this change, please." ?

**Comment by gizmocuz** [comment]
Thanks, i made the code change
