### ISSUE TITLE
Alert Sensor created with Python plugin can't be updated through JSON /MQTT

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#2005]
I created an alert sensor within a Python plugin. This device has unit(id) 6. If I update this sensor through json or mqtt the device isn't updated. This is probably while the plugin system cannot handle 'svalue'- strings.

In the past, the alertsensors were updated, but a percentage or text sensor was duplicated. I do think there are two things that are not implemented correct yet:
- The plugin command message should accept svalue strings
- The general device should not be using the 'unit' number if a device is created by the plugin system

**Comment by guillaumezin** [comment]
First part should be corrected by https://github.com/domoticz/domoticz/pull/2013

**Comment by ghost** [comment]
Just pulled the latest development branch, but still the same problem...:(

**Comment by sweetpants** [comment]
Maybe not commited yet?

**Comment by guillaumezin** [comment]
Nope, my proposal is not integrated in Domoticz development branch yet...

**Comment by gizmocuz** [comment]
It seems there are backwards compatibility issues with this pull request and it can not be accepted

**Comment by ghost** [comment]
Are there? It seemed to me there is an optional parameter added. For me this is must have functionality (default functionality is broken) and I have to migrate to OpenHAB. Something I'm trying to avoid for the last month, but I'm running out of time unfortunately...

**Comment by guillaumezin** [comment]
Well, I first proposed an optional parameter and it wasn't accepted, then I proposed a 4th parameter to onCommand and there are still discussions on the way it will break current plugins...

**Comment by gizmocuz** [comment]
Should be solved now. Can we close this issue ?

**Comment by guillaumezin** [comment]
The request can be implemented with #2083 @Ullie do you confirm?

**Comment by gizmocuz** [comment]
No feedback received, assuming it is solved.
