### ISSUE TITLE
Timer on Selector not working anymore

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2451]
See, https://www.domoticz.com/forum/viewtopic.php?f=6&t=23620

Verified on V3.9546 too

![image](https://user-images.githubusercontent.com/23421160/40795445-658b5fae-6502-11e8-80dc-1e1a8392bb36.png)

**Comment by gizmocuz** [comment]
Seems to be caused by this code in the timers controller

`vm.isCommandSelectionDisabled = vm.isSelector && device.LevelOffHidden;`

Should a selector switch be able to have timers ?

So i edited my dummy selector switch, and disabled hiding the off level, now i can edit the timers

So i can set it to On or Off, that seems wrong as i have 5 levels, with other names

So question:
- did this worked before ?
- what was 'On' supposed to trigger, what level ?
- what was 'Off' supposed to trigger, what level ?

We should rebuild it so it used the level names

**Comment by gizmocuz** [comment]
My bad, found the answers... the selector switch is build in a rather complex way

Solved in beta 9546

**Comment by sweetpants** [comment]
Not quite yet, still cannot select a command for the level selected, or I don't understand how it works.

![image](https://user-images.githubusercontent.com/23421160/40838038-b201529a-659c-11e8-8845-555df1df55c0.png)

**Comment by sweetpants** [comment]
My bad, off course you can only select 'On'.

**Comment by gizmocuz** [comment]
@sweetpants , yes, it is a bit confusing when 'Hide Off Level' is enabled

**Comment by gizmocuz** [comment]
Actually, instead of disabled, let's make this invisible...

**Comment by sweetpants** [comment]
Yes, i think that is better

**Comment by gizmocuz** [comment]
Done in last commit, i see another issue, if you have added a normal switch, then change it's type to selector, it is not seen as a selector switch in the timer editor

Both have also a different subtype, the switchtype is set to selector

Original (created a selector switch from the dummy hardware)
Type: Light/Switch
SubType: Selector Switch
SwitchType: Selector

Changed a normal switch to selector:
Type: Light/Switch
SubType: Switch
SwitchType: Selector

![image](https://user-images.githubusercontent.com/2265299/40840625-cc64aa8c-65a7-11e8-9b8e-c4d3d4cbf0b0.png)

Solved in beta 9552
