### ISSUE TITLE
Temp log gone since commit #b5049dc

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2622]
V4.9805 shows no temperature logs anymore. I think this is related to changes in commit b5049dc

**Comment by kovainfo** [comment]
+1
I confirm. Temp log with humidity does not work

**Comment by gizmocuz** [comment]
Could be caused by #2612

**Comment by gizmocuz** [comment]
Should be solved now

**Comment by sweetpants** [comment]
Not quite, "WU Wind" sensor still shows no log. Temp, and Temp+Hum are ok now.
But maybe that is because it's a Wind sensor placed under Temperature showing temperatures?
![image](https://user-images.githubusercontent.com/23421160/43941905-30429118-9c76-11e8-9957-46dd03e3c9e6.png)

**Comment by gizmocuz** [comment]
I think this is because the type is 'Wind', does it show the wind log instead of the temp log ?
It should show something...

**Comment by sweetpants** [comment]
Nope, it shows nothing

**Comment by gizmocuz** [comment]
We might have an issue in the feature when the weather tab will also use the /Log functionality,
but for now the current beta version (9817) should solve this as well

**Comment by sweetpants** [comment]
At the moment it looks ok, case closed

**Comment by mrohner** [comment]
> Should be solved now

@gizmocuz, Solved how??

I'm running 4.9700 and temp logs suddenly disappeared, what should I do?

**Comment by harryd100** [comment]
@mrohner Update to latest Beta
