### ISSUE TITLE
Xiaomi Aqara wireless switches not working

### ISSUE THREAD

**Issue by twpeltenburg** [domoticz/domoticz#2730]
I have bought several Xiaomi Aqara wireless witches. They are not recognized by Domoticz, but they are listed as supported.

Xiaomi Wireless double switch
Xiaomi Wireless single switch

error: XiaomiGateway (ID=2): unhandled model: remote.b186acn01
error: XiaomiGateway (ID=2): unhandled model: remote.b286acn01

I have tested Domoticz v4.9700 stable and v4.10007 beta

**Comment by twpeltenburg** [comment]
I have found in the source code XiaomiGateway.cpp that the single wall switch should report as 86sw1 or 86sw2 but reports as  remote.b186acn01 or remote.b286acn01 in the log

**Comment by twpeltenburg** [comment]
proposed code: https://github.com/twpeltenburg/domoticz/commit/5055b26a645fcf9b4ec8a4d0e70d5e6cbaec2cc5

**Comment by kovainfo** [comment]
The logs should contain information about the channels. something like that: 
2018-09-27 18:26:23.158 Status: {"cmd":"heartbeat","model":"ctrl_ln1.aq1","sid":"158d0001f12345","short_id":28634,"data":"{\"voltage\":3600,\"channel_0\":\"off\"}"}
2018-09-27 18:26:38.343 Status: {"cmd":"heartbeat","model":"ctrl_neutral1","sid":"158d0001854321","short_id":9647,"data":"{\"voltage\":3300,\"channel_0\":\"off\"}"}

i.e. need heartbeat status

**Comment by twpeltenburg** [comment]
Solved in newest beta.

**Comment by robgardien** [comment]
I still have this issue in the latest beta, what could be the problem?
