### ISSUE TITLE
Rain week

### ISSUE THREAD

**Issue by Derf911** [domoticz/domoticz#2736]
Hello,

I use Domoticz version V4.10007 (bêta) and I get precipitations from DarkSky.
The weekly counters are zero : https://ibb.co/iMg0p9 

Is it a bug ?

Thanks for your help,

**Comment by gizmocuz** [comment]
Looks like it... do you have any day values (in the month/year graph) ?

**Comment by Derf911** [comment]
I have values in the month and year graphs.

**Comment by gizmocuz** [comment]
@Derf911 , could you contact me on the forum ? I would like to investigate this further

**Comment by sweetpants** [comment]
@GizMoCuz, this is the same issue as the "incremental counter" These also show no week graphs https://www.domoticz.com/forum/viewtopic.php?f=6&t=23911

**Comment by gizmocuz** [comment]
Should be fixed for now (reverted a patch)

**Comment by sweetpants** [comment]
Should I open a separate topic for Incremental Counter Week graphs? They still don't work

**Comment by gizmocuz** [comment]
@sweetpants, yes, this is about Rain... if you got my mail address, a database export and screenshot would be helpfull

**Comment by sweetpants** [comment]
Send you a database backup and screenshot

**Comment by gizmocuz** [comment]
@sweetpants , it seems it was never implemented, so it has never worked...
Should work now in new beta
