### ISSUE TITLE
Issue with rain graph from DarkSky

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#3109]
Since WU is not working anymore since they closed the free API, I switched to DarkSky.
Nice service!
But, the week and month graphs are incorrect.
See screenshot. It rained a lot today, but the week graph is hangen on 0 mm...
Maybe something to do with issue https://github.com/domoticz/domoticz/issues/2736?

For the today week state, I see the row SELECT Total, Total, Rate FROM Rain WHERE (DeviceRowID=%" PRIu64 " AND Date>='%q') ORDER BY ROWID DESC LIMIT 1. (WebServer.cpp line 14551) So I can imagine that this will stay on 0 forever due to the order by rowid desc and limit 1. Doesn't have this row to do some calculations or something?
![afbeelding](https://user-images.githubusercontent.com/25199588/54090973-9e27f280-437a-11e9-81a8-c27793d25a23.png)

**Comment by Olifant1990** [comment]
I am close to a solution. Just need some tuning and testing. Hang on!
It was needed to rebuild the calculation logic, because you only get a rainRate from DarkSky, no rain totals.
Herefore I needed to make a new subtype for DarkSky.

**Comment by gizmocuz** [comment]
@Olifant1990 , i think we get a daily rain, not a total rain.
The rain-rate is something different, this is the amount of rain in the last hour
But maybe a more generic sensor name for the new rain sensor is better ? It could be used by other hardware as well

**Comment by Olifant1990** [comment]
No, we get a precipIntensity only from DarkSky, which is described as "The intensity (in inches of liquid water per hour) of precipitation occurring at the given time. This value is conditional on probability (that is, assuming any precipitation occurs at all)."
So we get only for example a rainrate of 0.5 mm/hour at current time.
Then we need to calculate this and get a total for our selfs over the day.
All this is working at my testversion right now and seems ok, but need some real rain, it is dry for a few days here or I wasn't home those rainy days :P
I will give it a more generic name. Like sTypeRAINRate?
Have sneak preview at https://github.com/domoticz/domoticz/pull/3125
I closed it because a lack of testing

**Comment by gizmocuz** [comment]
Sounds very bad, and not good at all ... Sure the rain rate will be adjusted during an hour... you can not use this for a counter
01:00-02:00 5mm rain, started at 01:15
01:20- 3 mm rain.. the 2mm from 01:15 is already taken out
It keeps on changing

As this is not reliable, i would suggest to drop support

Bdw, WU is working again

**Comment by gizmocuz** [comment]
Another option:

https://www.weerstationexpert.nl/tfa-30.3161-regensensor

**Comment by Olifant1990** [comment]
No, I worked it out a little bit different I guess.
For example:
The following readings (mm are a bit "high" to make the calulations easier)

00:00 rate is 60 mm/hour, total 0
next reading is 5 minutes later (default update rate for Darksky), still a rate at 60 mm/hour.
now, itterate over past rows of today and calculate total over the time taken already
5 minutes past sinds 00:00, so rate/60 minutes x minutes past: 60/60*5 = 5mm
next row in database will be writen: 
00:05 rate is 60 mm/hour, total is 5mm for now.
Next reading at 00:10 for darksky: 0 mm/hour rate
itterate: 00:00-00:05 is 5 mm + 00:05-00:10 is also 5:
Write new row in db 00:10 0mm/hour current total is 10 mm
and so on.

I know this is the best we can get out of only a rate/hour given, but it is as accurate as I can get it for DarkSky.
The last tests I've done in another city where it rained, the measurements are very close.
Let say may day total was 0.7 and if I look in wheater statistics, they say 0.8 or 0.6 in almost same region.
So, I will push this fix for those people who wants to stay with DarkSky. They can get a rain device as accurate as possible.

See https://github.com/domoticz/domoticz/pull/3131

**Comment by Olifant1990** [comment]
Also a sidenode: The new WU API is only accessible by PWS owners who are sending their data to WU.
So, I still have no API key ;)

**Comment by Olifant1990** [comment]
Solved by https://github.com/domoticz/domoticz/pull/3131

**Comment by miroslavpetrov** [comment]
I upgraded domoticz to latest beta but I still have problem with the rain sensor. The log file says:

`2019-05-17 22:47:29.924 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 1 elements received ("233.490"), notification not sent (Hardware: 4 - Weather, ID: 1, Unit: 0, Type: 55 - Rain, SubType: 113 - Unknown)`

**Comment by Olifant1990** [comment]
@miroslavpetrov Could you just create a new issue?
And then tell everyone the exact details?
- What hardwaretype? DarkSky?
- What latest beta version number?
Etc.

Because at my side everything is working ok,
Oh and maybe you can tell what is possibly triggering this error. Do you have events on it? Lua, blockly?

**Comment by etsach** [comment]
Hi,
I made some tests on the DarkSky rain data. I took the hourly precipIntensity values at every hour : 00:00 , 01:00, ... , 23:00 from the 'time machine'
If you sum up these values, then you get a daily total which is exactly the same as the nearby airport weather station.

So I think that if you query an hour in the past, for instance you ask for 05:00 at least at 06:00 (and a little bit more in order to be sure that the final value has been updated in DarkSky), then you get a proper hourly cumulative value. Then you can update the Domoticz Rain Device counter using this. The "instant" value from darkSky can be used to display the instant rate.

I will make some test but I think it should work.

**Comment by Olifant1990** [comment]
Indeed, I know, but then you need 1 more request every hour instead of the current requests every 10 minutes. And rain rate and totals are a bit clustered in Domoticz right now.
