### ISSUE TITLE
Temporary override not visible in the API

### ISSUE THREAD

**Issue by Jaap-Jan** [domoticz/domoticz#373]
Setting a temporary override works as expected (if I set an override via the web interface, the controller is also updated). The web interface briefly shows the correct status 'TemporaryOverride' before restoring it to 'Auto'. In the controller you can see that the override is still in effect.

**Comment by gizmocuz** [comment]
Please create a pull request

**Comment by Jaap-Jan** [comment]
You may close this one as well. I haven't fixed the issue and I don't know how to fix it.

**Comment by gizmocuz** [comment]
What hardware device ? It could be that the new status is polled, but that you receive old data
is this also after lets say 15 minutes ?

**Comment by Jaap-Jan** [comment]
I use the Honeywell HGI80. I haven't checked, but I will check that when I'm home.

**Comment by Jaap-Jan** [comment]
I've checked this and even after a few hours the returned status is 'Auto', not 'TemporaryOverride'.

**Comment by gordonb3** [comment]
Likely fixed with revision 3.4944

**Comment by gizmocuz** [comment]
Great, and is it fixed?

**Comment by Jaap-Jan** [comment]
Updated Domoticz to 3.4967 (current beta), but unfortunately this patch doesn't seem to help. Still the same symptoms as before.

**Comment by gizmocuz** [comment]
What hardware device is this? (In Domoticz)
It is still not clear for me... You talk about Honeywell... We do not have a Honeywell hardware device

**Comment by Jaap-Jan** [comment]
I'm sorry, the device in Domoticz is called "Evohome USB (for HGI/S80)". The HGI-80 is an USB device to communicate wirelessly with an Honeywell Evohome controller.

**Comment by gordonb3** [comment]
Just for clarity: what are you setting exactly? The override showing in domoticz web UI is because the code simply assumes a success without polling the result. Changing back to auto means that the central unit did not register the override and thus reports the zone to follow the normal schedule.

There's something of a feature here: the central unit will only register changes to zones. Meaning that if you change the setting of a single radiator controller it will not show on the central unit and consequently the RFG100 and/or HGI80 will not report the override - even if that radiator is the only zone member. So when you say "controller", are you then referring the central unit or the radiator controller (HR92/HR80)?

**Comment by Jaap-Jan** [comment]
1) By "controller" I mean the central unit, or as Honeywell calls it, the "central controller". In this case the ATC928G2000.
2) In Domoticz, I'm setting a new set point for a single zone, with an end date. And the central unit DOES pick up on it because it's showing a clock and the "Total connect comfort app" also sees it, so the RFG-100 also reads the correct state. So it's the code (in Domoticz) that reads back the zone state using the HGI-80 that's at fault here.

**Comment by gordonb3** [comment]
That or the the HGI80 is giving false information. I found an interesting comment in the source:

> ```
>             //It appears that the controller transmits the current setpoint for all zones periodically this is presumably so 
>             //the zone controller can update to any changes as required
>             //The zone controllers also individually transmit their own setpoint as it is currently set
>             //presumably this will ordinarily update to correspond to the transmitted value from the controller
>             //The exception appears to be for local overrides which may be possible to track by seeing if a change
>             //occurs that does not correspond to the controller setpoint for a given zone
> ```

It would seem from this that unlike the RFG100 that is bound to a single device (i.e. the central controller) the HGI80 picks up on every message that is being sent by any active device in the system. It is therefore possible that the override status as reported by the central controller gets overwritten by a zone controller or zone valve that is not aware of schedules and overrides. It should still report the correct setpoint from the override though I think?

**Comment by gerloh** [comment]
I have the same issue with overrides. Also a timezone issue. When setting the override with a time this time is shifted 2 hours at the evohome controller. Do you have that too Jaap-Jan? 
I see you had a fix for this @gordonb3 , but i still have the timezone issue with the latest beta. I see the shifted time already in the temporyOveride shortly in the dashboard before it is lost.

**Comment by gordonb3** [comment]
Negative. The invalid time issue had to do with setting a permanent override and caused the override either not to be accepted or expire instantly. I did find some inconsistencies with evohome time settings just recently though. I myself use an RFG100 and I found that when setting times I need to use UTC and overrides are also reported in UTC. Schedules however are reported in localtime. Now I can't tell what the HGI80 does, but from what I gather Domoticz itself changed from using localtime internally to UTC some time ago and it would seem likely that this switch is related to the time shift you are seeing. With scripted evohome I get all times displayed correctly.

**Comment by Evsdd** [comment]
I also have the issue with overrides only briefly appearing for zones monitored via the Evohome HGI80.  I think I have a fix as I believe the issue is caused by the use of sizeof in ConvertMode in evohome.h . Based upon my testing, this can generate incorrect array sizes which prevent correct conversion of the override messages and they default to Mode 0: Normal.

**Comment by gerloh** [comment]
Ah that would be great. @gizmocuz : could you review and merge his pull request ?

**Comment by Evsdd** [comment]
Thanks for your support.  I've got a different pull request pending at present [#627] on another Evohome HGI80 issue (multi-room zone temperatures not updating) and once this is sorted out I'll be able to create a new pull request to resolve this missing override issue.

**Comment by gizmocuz** [comment]
Patch is merged

**Comment by Jaap-Jan** [comment]
Seems to work. Thanks Evsdd for fixing this. :+1:
