### ISSUE TITLE
Door contact with custom icon shows incorrect state on floorplan

### ISSUE THREAD

**Issue by mikewoudenberg** [domoticz/domoticz#3849]
I'm using custom icons for showing whether the windows in my home are open or closed. 
These show up alright in my switches tab (showing a closed window icon when the window is closed and an open window icon when the window is closed). When I look at my floorplan however I always see those icons showing open windows. If I hover over the window in the floorplan it shows "Closed" but the icon remains open.

![Screenshot from 2020-01-15 10-07-10](https://user-images.githubusercontent.com/5583336/72420387-eb38da00-377e-11ea-8cab-5f7d1c4cafe7.png)
![Screenshot from 2020-01-15 10-06-27](https://user-images.githubusercontent.com/5583336/72420391-ebd17080-377e-11ea-81f4-b3941f8649f2.png)

It is working properly foor the default icon, but I prefer the custom icon.
I'm currently running domioticz 4.11605 (build hash 7de1f368f) and I try to keep the beta up to date.

**Comment by gizmocuz** [comment]
Thanks for reporting. Should be solved in beta 11624

**Comment by Domoke12** [comment]
Hi, I have the latest version (Version: 2020.2)
but I also still have this problem. Status is correct but icon is not.
tried with clearing cache in Edge,Firefox and Chrome
