### ISSUE TITLE
Error uploading Iconset: undefined | beta v4.11648 custom icon issue

### ISSUE THREAD

**Issue by MacieIKS** [domoticz/domoticz#3865]
Using latest beta V4.11648
Not able to upload correctly archived custom icon set (48px x 48px). After choosing .zip file and clicking Upload, after 10 ses I am getting error message: Error uploading Iconset: undefined.
I have tried on Safari / Chrome (also in private mode), no change.

**Comment by gizmocuz** [comment]
Could you post a link to your iconset ?

**Comment by MacieIKS** [comment]
Here it is:
https://www.dropbox.com/s/5520vc7ch1covli/Heater.zip?dl=0

This iconset I was able to upload before, now with another instance of Domoticz, on latest beta release it is not possible. Also there is a topic on domoticz forum, where other users meet similar issue.

Appreciate your help.

**Comment by gizmocuz** [comment]
... please also mention the forum topic here

**Comment by MacieIKS** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=28&t=30754

**Comment by gizmocuz** [comment]
Should be fixed in the latest beta... could you test this ?

**Comment by MacieIKS** [comment]
Domoticz updated to beta v4.11657. Unfortunately error remains.

**Comment by gizmocuz** [comment]
Tested again and no issue here with this icon
Please try again on a new system.... You also did not follow the issue rules and reported your hardware platform
If it is a raspberry pi, you used the default 1 line sudo command to install Domoticz ?
(No changes in usernames, file/folder rights etc ?)
Please try on a clean system, or install the windows version and test with this
