### ISSUE TITLE
Another RTL433 Unhandled Sensor

### ISSUE THREAD

**Issue by jsgra1** [domoticz/domoticz#4150]
Hope someone can help as struggling to find out what is wrong / how to fix...

Pi 2B using with Domoticz,  Evohome, Nooelec Smart SDR, Oregon-THGR122N and Apollo oil tank sensor.

All seems to be working fine (regular updates for temperature / humidity and oil depth sensors, dzVents working to script oil level) but I keep getting unhandled sensor messages:
![image](https://user-images.githubusercontent.com/65082129/81479150-8ca9d700-9219-11ea-89cf-106edfca8a81.png)

[Errorlog.txt](https://github.com/domoticz/domoticz/files/4604079/Errorlog.txt)

Any help appreciated.

**Comment by gizmocuz** [comment]
@jsgra1 , seems the header line is getting bigger and it could be that there was not enough room to parse it.
Could you try beta 12020, I increased the buffer by 1024 bytes
Maybe there is a command line argument that could tell RTL433 only to return the headers/values actually in use ?

**Comment by jsgra1** [comment]
Thanks for lookig into this and the response.

Tried with the beta build (hope it was correct to set beta in Settings, then Update and Restart).

Same issue unfortunatley (see log file), but also seems to be affecting other sensors I'd not seen it error with before.

Afraid I can't find an argument to restrict output on RTL433. Tried running natively and I can't identify the issue (rtl_433 with no arguments chugs away for hours with nothing untoward. That said with -vv or -vvv options I don't really know what to look for).

[ErrorLog - Beta Build.txt](https://github.com/domoticz/domoticz/files/4605973/ErrorLog.-.Beta.Build.txt)

**Comment by gizmocuz** [comment]
@jsgra1 , I think it is time that we move to the JSON output format.
I need some time for this, maybe it is not that difficult as it seems all field names are the same as in the CSV ouput

**Comment by jsgra1** [comment]
@gizmocuz Many thanks for the JSON update - unfortunatley the same issue still:

[ErrorLog - JSON Build.txt](https://github.com/domoticz/domoticz/files/4611244/ErrorLog.-.JSON.Build.txt)

Not sure if relevent but running with same arguements natively, no errors but each temp reading is duplicated with same timestamp (can do a longer run if needed):

[ErrorLog - Native.txt](https://github.com/domoticz/domoticz/files/4611261/ErrorLog.-.Native.txt)

**Comment by gizmocuz** [comment]
@jsgra1 , seems the internal pipe gets broken....
Could you try beta 12039, the internal buffer is now build differently

**Comment by jsgra1** [comment]
@gizmocuz - been having a few troubles with this one! 

When I updated, I could no longer acces the web site. On reversion to the stable release it was back to normal (i.e. with the original errors). Tried the same process using the updatebeta script and the same thing.

Rebuilt the pi from scratch (just in case) and the same thing.

Rebuilt again without RTL_433 configured in Hardware and the updatebeta was fine.

On adding RTL_433 in Hardware it again stopped.


Errorlog from restarting after upgrade:

[ErrorLog - 12039 Build.txt](https://github.com/domoticz/domoticz/files/4618205/ErrorLog.-.12039.Build.txt)

Also messages and syslog if it helps

[messages.txt](https://github.com/domoticz/domoticz/files/4618235/messages.txt)

[syslog.txt](https://github.com/domoticz/domoticz/files/4618237/syslog.txt)

**Comment by gizmocuz** [comment]
@jsgra1 , sorry about this, worked great on my development system (windows)
I changed it back to the original method (fgets) but now checking if we received part of the output line and if so we add the next read to it.
Could you check version 12047 ?

**Comment by jsgra1** [comment]
@gizmocuz - thanks again but tried the latest build (12409) but unfortunatley the same issue as 12039.

[ErrorLog - 12049 Build copy.txt](https://github.com/domoticz/domoticz/files/4620682/ErrorLog.-.12049.Build.copy.txt)

**Comment by gizmocuz** [comment]
@jsgra1 , sorry found the issue ! Was using a nullptr instead of the open handle under non-windows systems
New update available

**Comment by jsgra1** [comment]
@gizmocuz - thanks - it's working now but unfortunatley the same "Rtl433: Unhandled sensor reading".
[ErrorLog - 12052 Build.txt](https://github.com/domoticz/domoticz/files/4622071/ErrorLog.-.12052.Build.txt)

**Comment by gizmocuz** [comment]
@jsgra1 Please try beta 12055, this should be working

**Comment by jsgra1** [comment]
@gizmocuz - sorry but still not working and I think it may be dropping some readings as there are significant gaps in the timeline at some points - the "(RTL433) Temp + Humidity (Outside)" should ping ~twice a minutue.

[ErrorLog - 12055 Build.txt](https://github.com/domoticz/domoticz/files/4623336/ErrorLog.-.12055.Build.txt)

**Comment by gizmocuz** [comment]
@jsgra1 , could you try on another system, a Linux and windows perhaps ?
Maybe you need a powered USB hub, or your power supply is insufficient

**Comment by jsgra1** [comment]
@gizmocuz - don't think it is low power (no alerts from Pi and running RTL natively works OK) but will try Windows or Mac and will revert (probably this weekend before I get a chance though).

**Comment by jsgra1** [comment]
@gizmocuz - apologies for the delay responding but a series of issues meant that I ended up buying a new Pi 4. It is running fine with the JSON beta - perhaps one or two errors every 24 hours (the device sends a message every minute so no issue really), just odd.

[ErrorLog - 12106 Build.txt](https://github.com/domoticz/domoticz/files/4707583/ErrorLog.-.12106.Build.txt)

**Comment by gizmocuz** [comment]
@jsgra1, this is the log line from your document:

{"time" : 2020-05-31 09:36:24", "brand" : "OS", "model" : "Oregon-THGR122N", "id" : 53, "channel" : 1, "battery_ok" : 1, "temperature_C" : 16.700, "humidity" : 52}

Is this correct ? Did you copy/paste this ?

Because if you look at the "time" field, you are missing a opening quote

If I add this quote, it is parsing correctly:

{"time" : "2020-05-31 09:36:24", "brand" : "OS", "model" : "Oregon-THGR122N", "id" : 53, "channel" : 1, "battery_ok" : 1, "temperature_C" : 16.700, "humidity" : 52}

**Comment by jsgra1** [comment]
@gizmocuz - Apologies but I can't explain the missing quote and haven't got the original log any more - maybe I deleted it in error when copied across. It errors now only occasionally (maybe once a day). Another log entry attached - can't see any missing quote in this one.

[ErrorLog - 12106 Build.txt](https://github.com/domoticz/domoticz/files/4740039/ErrorLog.-.12106.Build.txt)

**Comment by dgrostoto** [comment]
same problem with quote around the battery_ok field this time.

**Comment by jsgra1** [comment]
@gizmocuz @dgrostoto - Yes indeed - I dumped a few days worth of the log and every unhandled error (there is normally 1 event every second so not many errors) has a missing character (not just quotation marks, but others as well). So I guess either RTL433 is randomly not formatting correctly or characters are being dropped somewhere along the line. Any way to dump the output of RTL or get Domoticz to tee it to a file as well process them?

[Unhandled RTL433.log](https://github.com/domoticz/domoticz/files/4805765/Unhandled.RTL433.log)

**Comment by waltervl** [comment]
This issue has been solved in some way?
