### ISSUE TITLE
Z-wave reports interval not working

### ISSUE THREAD

**Issue by NiekN** [domoticz/domoticz#4298]
At my Domoticz , i have also z-wave sensors working, it worked fine for some years
But now after an update it looks like it is not working anymore

The sensors are working correctly , when some value is changed it will update domoticz. But when the temperature is stable or the lux light sensor is stable (at night) it will not update anymore even when parameter is set:,
42. Luminance reports - interval: 900 (seconds) (actual: 900)

This parameter should mean, also when there is no changed of value an report will be send after 15min
But i see that it is not working anymore , i get timeouts ..

Im running Version: 2020.2 (build 12257)

It there something changd in an update ?

**Comment by gizmocuz** [comment]
@NiekN , No there have been no changes to this.
You might want to add some information about the hardware you have
Check the documentation to see if periodic updates are send to another Group then 1, and if your controller (node 1) is in that specific group
Does it report during the day in 15 minute intervals ? You could make a dzVents scripts that reacts on a lux up, and create a custom sensor that logs the time (in minutes) between this update and the previous update, you should then have a good overview
mydevice.lastUpdate.minutesAgo

**Comment by RDols** [comment]
@NiekN
This is a coincidence. For some other reasons i'm looking into ZWAVE stack and the implementation in domoticz. One of the things i run into is that e.g. power meter is turned off, domoticz thinks is is offline. I run into a simular problem. Reason for this that the zwave stack will send a "Type_ValueRefreshed" or "Type_ValueChanged" depending if the value has changed. But Domoticz does not update the internal value/timestamp on "Type_ValueRefreshed".

@gizmocuz 
This behaviour is not new, and traced it back to the subversion import many years ago. Is there a special reason the "UpdateValue" in the "Type_ValueRefreshed" handler (OpenZWave.cpp line 633) is commented out? The behaviour of Domiticz should handle this well when it's active again. I currently have this active for two weeks no in my debug build.

If you think this is ok, i would like to create a pull-request for this.

**Comment by NiekN** [comment]
@RDols 
Thx for clearify , hopefully the update will be done soon

**Comment by gizmocuz** [comment]
@RDols , I am not sure why it was commented out...
Could it be that when this enabled there are two udates:

```
Type_ValueChanged
Type_ValueRefreshed
```

Does Type_ValueRefreshed means the value is also changed ? Or just refreshed ?
If it is not changed, maybe only set:

`nodeInfo->LastSeen = m_updateTime;`

**Comment by RDols** [comment]
@gizmocuz 
If a valua has received bij openzwave only one of those two messages is send. With "Type_ValueRefreshed" the value didn't change since the last time. This has a few catches with KWh meters in OpenZWave.

During a meter update, two different values are send: Watt and KWh. The message applies to KWh value. If there is very small usage, it could take a while before the kWh counter changes (typically after 10Wh), but the watt can change. Or when the power consumption stopts, domoticz always shows a old none zero "Watt" usage just before it was switched off.

I didn't try only updating the LastSeen. I will check if that has same effect.

**Comment by RDols** [comment]
@gizmocuz
Just setting the LastSeen doesn't work. meters become red again. In retrospective, this is to be expected...

Enabling the update should not give an problems, and solves some (rare) cases not receiving the latest power (Watt) and missing history when there is no usage. That this also going to apply for e.g. switches, doesn't seem to effect domoticz.

**Comment by gizmocuz** [comment]
@RDols , About the switches, I guess that is because we check (in the openzwave.cpp class) if the status has been changed or not)
Shall we merge the PR ?

**Comment by RDols** [comment]
@gizmocuz
I do not know all the inside details and corners of domoticz. But it is handled well. Other hardware classes sends received values to the internal domoticz without filtering. I didn't find any reason not to.

I would say go ahead with the merge.

**Comment by NiekN** [comment]
looks like it is solved at Version: 2020.2 (build 12279)
i had no time-outs last night... thx for support

**Comment by gizmocuz** [comment]
Time-outs that you see in the log are coming from OpenZWave and not Domoticz, you will still see them as it is not solved with this patch.
If you mean time-outs by that a sensor in Domoticz turns red because there have been no recent updates , then yes this patch could solve this. (And you do not see time-out messages in the log)
Otherwise, sometimes by disabling/enabling the openzwave hardware could solve the time-out problem

**Comment by gizmocuz** [comment]
@RDols , thanks for the patch! Closing issue!
