### ISSUE TITLE
Can't change MQTT Publish Topic / CA Filename

### ISSUE THREAD

**Issue by mhwlng** [domoticz/domoticz#444]
Synology DS716+
Version: 2.4461
Build Hash: 59e315f-modified

Setup\Hardware

MQTT Client Gateway with LAN inteface:

Publish Topic : Flat
CA Filename : empty string

I can't change above two items. 
They always revert back to the default.

I can change any other field (e.g. remote address, port, user name, password) without problems.

**Comment by gizmocuz** [comment]
There seems to be no problem with it
Try adding a new MQTT (with for example IP/Port 127.0.0.1/1234)
leave ca empty
now select it from the list, then change the parameters and press update

**Comment by mhwlng** [comment]
Unfortunately, that also does not work for me.

When I am on the hardware screen all is ok, I can navigate to other hardware devices, then click on MQTT again, and I see the correct settings for publish topic and ca filename.

however, when I then go to device or log or some other screen, then go back to hardware and select MQTT. I don't see the correct Publish Topic/CA filename anymore (only these two fields have a problem)

**Comment by nayrnet** [comment]
I see same behavior as mhwing, those features do not really seem to be functional.

**Comment by gizmocuz** [comment]
Are we talking about 'functional' or about editing the settings in the Gui ? Because in the Gui it is working

**Comment by mhwlng** [comment]
Both:

GUI : 

When I am on the hardware screen all is ok, I can navigate to other hardware devices, then click on MQTT again, and I see the correct settings for publish topic and ca filename.

however, when I then go to device or log or some other screen, then go back to hardware and select MQTT. I don't see the correct Publish Topic/CA filename anymore (only these two fields have a problem)

Functional : 

I only ever see the 'out' MQTT topic.
I do have a working floorplan

**Comment by gizmocuz** [comment]
Thanks for the walk through... i can see it now, fix in progress!

**Comment by gizmocuz** [comment]
Should be fixed in latest commit, beta 4513

**Comment by mhwlng** [comment]
Thanks,

I now switched to :
Domoticz V2.4513 
Build Hash: 899f76e-modified,

the GUI problem is solved, but I still can't see any hierarchical MQTT Topic

publish topic combined or flat -> returns only domoticz\out
publish topic hierarchical -> returns nothing

I have a floorplan defined:
-roomplan office : 3 devices
-roomplan outside : 3 devices
-floorplan : house with roomplan office and outside

**Comment by gizmocuz** [comment]
I think the options should read:

```

                        <option value="1">out</option>
                        <option value="2"><Floor>/<Room></option>
                        <option value="3">out + <Floor>/<Room></option>

```

it looks like it is implemented in the code, are you able to debug ?

**Comment by mhwlng** [comment]
ok, I found out why it wasn't working :

I use virtual sensors and some lua code, to split temp+humidity+baro into 3 separate devices.

If I add the original 'temp+humidity+baro' device to the room plan it works ok.
I see domoticz/out/house/office

If I add the virtual sensor 'temp' to the room plan, it doesn't work
I only see domoticz/out

**Comment by gizmocuz** [comment]
virtual sensors are only updated in domoticz
thanks for the feedback, closing topic
