### ISSUE TITLE
Domoticz beta #12623 crashes after 1 minute on rpi

### ISSUE THREAD

**Issue by TheReptile** [domoticz/domoticz#4449]
After updating to build #12623 the beta crashes on my rpi3 after 1 minute

Here is the crash:

```
Fatal Python error: Segmentation fault

Thread 0x7604e010 (most recent call first):
2020-11-09 18:08:00.499  Error: Domoticz(pid:15776, tid:15822('EventSystemQueu')) received fatal signal 11 (Segmentation fault)
2020-11-09 18:08:00.499  Error: siginfo address=0x3da0, address=(nil)

[...]

2020-11-09 18:08:04.527  Error: Thread 36 (Thread 0x5f1f5220 (LWP 15822)):
2020-11-09 18:08:04.527  Error: #0  __waitpid (options=0, stat_loc=0x5f1f3cc0, pid=16353) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-11-09 18:08:04.527  Error: #1  __waitpid (pid=16353, stat_loc=0x5f1f3cc0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-11-09 18:08:04.527  Error: #2  0x002e354c in dumpstack_gdb(bool) ()
2020-11-09 18:08:04.527  Error: #3  0x002e3b18 in signal_handler(int, siginfo_t*, void*) ()
2020-11-09 18:08:04.527  Error: #4  <signal handler called>
2020-11-09 18:08:04.527  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-11-09 18:08:04.527  Error: #6  <signal handler called>
2020-11-09 18:08:04.528  Error: #7  0x00261ff4 in CEventSystem::ParseBlocklyLua(lua_State*, CEventSystem::_tEventItem const&) ()
2020-11-09 18:08:04.528  Error: #8  0x002656d0 in CEventSystem::EvaluateDatabaseEvents(CEventSystem::_tEventQueue const&) ()
2020-11-09 18:08:04.528  Error: #9  0x00265cf8 in CEventSystem::EvaluateEvent(std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&) ()
2020-11-09 18:08:04.528  Error: #10 0x0026717c in CEventSystem::EventQueueThread() ()
2020-11-09 18:08:04.528  Error: #11 0x00999954 in execute_native_thread_routine ()
2020-11-09 18:08:04.528  Error: #12 0x76bf9494 in start_thread (arg=0x5f1f5220) at pthread_create.c:486
2020-11-09 18:08:04.528  Error: #13 0x76aac578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Segmentation fault
```

**Comment by salopette** [comment]
2020-11-09 18:59:33.871 Status: Domoticz V2020.2 (build 12623) (c)2012-2020 GizMoCuz
2020-11-09 18:59:33.871 Status: Build Hash: 3114ba8bf-modified, Date: 2020-11-09 16:04:05
2020-11-09 18:59:33.871 Status: Startup Path: /home/pi/domoticz/

domoticz stops for me after the start.
Reboot doesn't help

2020-11-09 18:56:19.071 Error: Domoticz(pid:876, tid:992('EventSystemQueu')) received fatal signal 11 (Segmentation fault)
2020-11-09 18:56:19.071 Error: siginfo address=0x36c, address=(nil)
Top

**Comment by salopette** [comment]
2020-11-09 19:28:24.158 Status: Domoticz V2020.2 (build 12623) (c)2012-2020 GizMoCuz
2020-11-09 19:28:24.158 Status: Build Hash: 3114ba8bf-modified, Date: 2020-11-09 16:04:05
2020-11-09 19:28:24.158 Status: Startup Path: /home/pi/domoticz/
2020-11-09 19:28:24.259 Status: PluginSystem: Started, Python version '3.7.3'.
2020-11-09 19:28:24.267 Status: WebServer(HTTP) started on address: :: with port 8089
2020-11-09 19:28:24.275 Status: WebServer(SSL) started on address: :: with port 443
2020-11-09 19:28:24.278 Status: Camera: settings (re)loaded
2020-11-09 19:28:24.344 Status: TCPServer: shared server started...
2020-11-09 19:28:24.345 Status: RxQueue: queue worker started...
2020-11-09 19:28:26.347 Status: XiaomiGateway (ID=14): Delaying worker startup...
2020-11-09 19:28:26.349 Status: Fritzbox: connected to: 192.168.178.1:1012
2020-11-09 19:28:27.347 Status: MQTT: Connecting to 192.168.178.37:1883
2020-11-09 19:28:27.548 Status: MQTT: connected to: 192.168.178.37:1883
2020-11-09 19:28:27.748 Status: MQTT: Subscribed

2020-11-09 19:30:51.999 Error: Domoticz(pid:1910, tid:1945('EventSystemQueu')) received fatal signal 11 (Segmentation fault)
2020-11-09 19:30:51.999 Error: siginfo address=0x776, address=(nil)

**Comment by michelscholte** [comment]
I've updated my Domoticz to the latest Beta version 2020.2 (12623) and after that Domoticz is crashing after several minutes.

**Comment by rwaaren** [comment]
Seems to be related to Blockly execution. When I create a Blockly to do something when a device is switched and I switch the device, domoticz crashes. dzVents scripts seem to be unaffected.

My domoticz can only be (re)started after a service domoticz stop but that's probably not directly related as I have seen this before

**Comment by rirethy** [comment]
Same problem here :

2020-11-09 21:30:23.279  Status: Domoticz V2020.2 (build 12623) (c)2012-2020 GizMoCuz
2020-11-09 21:30:23.280  Status: Build Hash: 3114ba8bf-modified, Date: 2020-11-09 16:04:05
2020-11-09 21:30:23.280  Status: Startup Path: /home/pi/domoticz/
[....]
2020-11-09 21:35:35.344  Error: #4  <signal handler called>
2020-11-09 21:35:35.344  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-11-09 21:35:35.344  Error: #6  <signal handler called>
2020-11-09 21:35:35.345  Error: #7  0x00261ff4 in CEventSystem::ParseBlocklyLua(lua_State*, CEventSystem::_tEventItem const&) ()
2020-11-09 21:35:35.345  Error: #8  0x002656d0 in CEventSystem::EvaluateDatabaseEvents(CEventSystem::_tEventQueue const&) ()
2020-11-09 21:35:35.345  Error: #9  0x00265cf8 in CEventSystem::EvaluateEvent(std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&) ()
2020-11-09 21:35:35.345  Error: #10 0x0026717c in CEventSystem::EventQueueThread() ()
2020-11-09 21:35:35.346  Error: #11 0x00999954 in execute_native_thread_routine ()
2020-11-09 21:35:35.346  Error: #12 0xb6b84494 in start_thread (arg=0xa5e7e220) at pthread_create.c:486
2020-11-09 21:35:35.346  Error: #13 0xb6a37578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6



As suggested above, I switch off all my blocky scripts, now it's OK.......
Hope it will be fixed soon.

EDIT....
In fact, still crashing, but after  more time. I have no time to investigate now.... I have deactivate all mu scripts even lua ones.

**Comment by bernardstef** [comment]
Oh, I'm not the only one, then ! Same problem here after the update.

**Comment by gizmocuz** [comment]
Found the issue... has to do with the recent PR that replaces a lot of for loops
New version will be available soon, going to test first and will report here when a new version is available

**Comment by rirethy** [comment]
> Found the issue... has to do with the recent PR that replaces a lot of for loops
> New version will be available soon, going to test first and will report here when a new version is available

Thanks a lot for your hard work !

**Comment by gizmocuz** [comment]
Version 12624 should solve the problem.
To update from a raspberry / ubuntu/debian, you can issue

cd domoticz
./updatebeta

(Still building at the moment for ubuntu/windows, should be ready in 10 minutes)

**Comment by bernardstef** [comment]
Hi,

Can confirm, seems to work great now !
Thanks for your hard work !!

**Comment by manubissanchez** [comment]
Hello,
I still have this bug on 2021.1.
Crash on cold start.
It seems to be related on this issue : https://github.com/domoticz/domoticz/issues/3371
How can I fix it ? Thanks :)

**Comment by bernardstef** [comment]
> 
> 
> Hello,
> I still have this bug on 2021.1.
> Crash on cold start.
> It seems to be related on this issue : #3371
> How can I fix it ? Thanks :)

I have this problem too, usually in the event of a power shortage I have to run Sudo reboot. it crashes on cold start after 30 seconds or so. Maybe related to a plugin ? I don't really know

**Comment by manubissanchez** [comment]
> I have this problem too, usually in the event of a power shortage I have to run Sudo reboot. it crashes on cold start after 30 seconds or so. Maybe related to a plugin ? I don't really know

It seems to be related on a sync issue, the Raspberry Pi having no RTC module. Basically, domoticz crash because the date/time is wrong. Maybe it's possible to make a script wich check the time and date and try to restart domoticz if it crash.
