### ISSUE TITLE
Fibaro Smart Implant FGBS-222 does not populate all device instances

### ISSUE THREAD

**Issue by robal** [domoticz/domoticz#4759]
Trying to get Fibaro Smart Implant FGBS-222 working.
Domoticz Version: 2020.2 (build 13133), running on Ubuntu 20.04 LXC container on x86
Z-Wave controller: USB Aeon Z-Stick 2E

After including it I expect (among others):
Two SWITCH BINARY devices representing two outputs.
Two SENSOR MULTILEVEL devices representing two inputs.
... and some others (internal temp, alarms, etc).

What I get (node 0x22) is:
![image](https://user-images.githubusercontent.com/5574519/113605665-dfb12780-963e-11eb-81b3-2781bca88b2a.png)
I don't think these are all devices. I can't see the sensor device representing one of the inputs (SENSOR MULTILEVEL)

Is the 'Domoticz will use the Dimmer (and hide the Switch)' functionality meant to de-duplicate some complex devices ? Is it erroneously removing them here ?

The log output after Z-Wave 'Refresh Node Info':
```
2021-04-05 17:41:04.262 Status: OpenZWave: Node Removed. HomeID: 23197859, NodeID: 34 (0x22)
2021-04-05 17:41:09.266 Status: OpenZWave: Received timeout notification from HomeID: 23197859, NodeID: 34 (0x22)
2021-04-05 17:41:12.923 Status: OpenZWave: A DNS Error Occurred
2021-04-05 17:41:14.180 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: SWITCH BINARY, Label: Instance 1: Switch, Instance: 1, Index: 0
2021-04-05 17:41:14.180 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: SWITCH BINARY, Label: Instance 2: Switch, Instance: 2, Index: 0
2021-04-05 17:41:14.180 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0
2021-04-05 17:41:14.180 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: CENTRAL SCENE, Label: Scene Count, Instance: 1, Index: 256
2021-04-05 17:41:14.496 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: SENSOR MULTILEVEL, Label: Instance 1: Voltage, Instance: 1, Index: 15
2021-04-05 17:41:14.815 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: SENSOR MULTILEVEL, Label: Instance 2: Voltage, Instance: 2, Index: 15
2021-04-05 17:41:14.180 Status: SendSwitchIfNotExists: Device '34.instance.1.index.0.commandClasses.48' (Sensor) with DeviceID '00002200' matches '34.instance.1.index.256.commandClasses.113' (Instance 1: Previous Event Cleared). Domoticz will use the Dimmer (and hide the Switch).
2021-04-05 17:41:15.136 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: SENSOR MULTILEVEL, Label: Instance 3: Air Temperature, Instance: 3, Index: 1
2021-04-05 17:41:15.294 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: CENTRAL SCENE, Label: Scene 1, Instance: 1, Index: 1
2021-04-05 17:41:15.294 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: CENTRAL SCENE, Label: Scene 2, Instance: 1, Index: 2
2021-04-05 17:41:16.736 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 1: Previous Event Cleared, Instance: 1, Index: 256
2021-04-05 17:41:16.736 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 1: Home Security, Instance: 1, Index: 7
2021-04-05 17:41:16.736 Status: SendSwitchIfNotExists: Device '34.instance.1.index.256.commandClasses.113' (Instance 1: Previous Event Cleared) with DeviceID '00002200' matches '34.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).
2021-04-05 17:41:16.736 Status: SendSwitchIfNotExists: Device '34.instance.1.index.7.commandClasses.113' (Instance 1: Home Security) with DeviceID '00002235' matches '34.instance.2.index.7.commandClasses.113' (Instance 2: Home Security). Domoticz will use the Dimmer (and hide the Switch).
2021-04-05 17:41:17.056 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 2: Previous Event Cleared, Instance: 2, Index: 256
2021-04-05 17:41:17.056 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 2: Home Security, Instance: 2, Index: 7
2021-04-05 17:41:17.376 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 3: Previous Event Cleared, Instance: 3, Index: 256
2021-04-05 17:41:17.376 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 3: Error Code, Instance: 3, Index: 266
2021-04-05 17:41:17.376 OpenZWave: Value_Added: Node: 34 (0x22), CommandClass: ALARM, Label: Instance 3: System, Instance: 3, Index: 9
2021-04-05 17:41:17.056 Status: SendSwitchIfNotExists: Device '34.instance.2.index.256.commandClasses.113' (Instance 2: Previous Event Cleared) with DeviceID '00002200' matches '34.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).
2021-04-05 17:41:17.056 Status: SendSwitchIfNotExists: Device '34.instance.2.index.7.commandClasses.113' (Instance 2: Home Security) with DeviceID '00002235' matches '34.instance.1.index.7.commandClasses.113' (Instance 1: Home Security). Domoticz will use the Dimmer (and hide the Switch).
2021-04-05 17:41:17.376 Status: SendSwitchIfNotExists: Device '34.instance.3.index.256.commandClasses.113' (Instance 3: Previous Event Cleared) with DeviceID '00002200' matches '34.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).
2021-04-05 17:41:23.797 Aeon Z-Stick 2E: General/Voltage (Voltage)
2021-04-05 17:41:23.957 Aeon Z-Stick 2E: General/Voltage (Voltage)
2021-04-05 17:41:23.676 Status: OpenZWave: Received timeout notification from HomeID: 23197859, NodeID: 34 (0x22)
2021-04-05 17:41:24.349 Aeon Z-Stick 2E: General/Alarm (Alarm Type: Instance 1: Home Security 7 (0x07))
2021-04-05 17:41:24.349 Aeon Z-Stick 2E: Light/Switch (Instance 1: Home Security)
2021-04-05 17:41:24.509 Aeon Z-Stick 2E: General/Alarm (Alarm Type: Instance 1: Home Security 7 (0x07))
2021-04-05 17:41:24.510 Aeon Z-Stick 2E: Light/Switch (Instance 1: Home Security)
2021-04-05 17:41:24.669 Aeon Z-Stick 2E: General/Alarm (Alarm Type: Instance 3: System 9 (0x09))
2021-04-05 17:41:24.670 Aeon Z-Stick 2E: Light/Switch (Instance 3: System)
2021-04-05 17:41:24.348 Status: OpenZWave: Alarm received (Instance 1: Home Security: Clear), NodeID: 34 (0x22)
2021-04-05 17:41:24.509 Status: OpenZWave: Alarm received (Instance 2: Home Security: Clear), NodeID: 34 (0x22)
2021-04-05 17:41:24.668 Status: OpenZWave: Alarm received (Instance 3: System: Clear), NodeID: 34 (0x22)
```

The node info in OZWCP panel looks OK and makes sense:
![image](https://user-images.githubusercontent.com/5574519/113606248-a927dc80-963f-11eb-858b-5c4b16912d86.png)

I should note that the switch devices representing outputs (SWITCH BINARY) are working as expected.

**Comment by gizmocuz** [comment]
Sorry I don't see the problem. You can operate the device with the switches. You have the temperature sensor, you have the voltage sensor.
You have the alarms
Note that you probably only see the other voltage sensor when there is actual voltage reported

**Comment by robal** [comment]
Thanks for swift reply @gizmocuz 
I've taken a thorough look while applying different voltages to both inputs.
Both inputs report to the same (one) device in Domoticz.
Log messages are exactly the same for both, eg:
```
2021-04-06 18:15:02.366 Aeon Z-Stick 2E: General/Voltage (Voltage)
2021-04-06 18:15:02.367 Python: Changed: ID: 1554 Name: Voltage, Type: 243, subType: 8, switchType: 0, s_value: 11.130, n_value: 0, n_value_string: 11.130, last_update_string: 2021-04-06 18:15:02 
```
The device 1554 gets updates from both inputs. The last reading is of whichever input happened to report last.

BTW: The above problem only applies when inputs are configured as 'analogue inputs'.
'button' modes seems to be working well and apply state to two separate instances of 'switch' device.

**Comment by gizmocuz** [comment]
@robal, thank you for testing. Is the voltage correctly reported if you look in the zwave control panel ? (like in your screenshot above)

**Comment by robal** [comment]
> 
> 
> @robal, thank you for testing. Is the voltage correctly reported if you look in the zwave control panel ? (like in your screenshot above)

Yes both instances report correct voltage on their respective input.

**Comment by gizmocuz** [comment]
@robal , are you able to compile yourself ?
Could you try changing the following code in ZWaveBase.cpp from

SendVoltageSensor(0, lID, BatLevel, pDevice->floatValue, "Voltage");

to

SendVoltageSensor(lID, 0, BatLevel, pDevice->floatValue, "Voltage");

**Comment by robal** [comment]
Tried it. Now it creates device with different ID, but it behaves the same way (gets competing updates from both inputs)

**Comment by gizmocuz** [comment]
Is it possible from the drop down menu to download the configuration file, and copy/paste the part for this node that specifies the voltage sensors ? (with index/instance number), I am currious about this

**Comment by robal** [comment]
Here it is. Note that I've used original Domoticz beta (not my build) to do this:
```
            <Value type="decimal" genre="user" instance="1" index="15" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.00">
                <Help>Voltage Sensor Value</Help>
            </Value>
            <Value type="decimal" genre="user" instance="2" index="15" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="11.93">
                <Help>Voltage Sensor Value</Help>
            </Value>

```

**Comment by gizmocuz** [comment]
Thank you for this

Is it possible to modify the function like above from

Could you try changing the following code in ZWaveBase.cpp from

```
	else if (pDevice->devType == ZDTYPE_SENSOR_VOLTAGE)
	{
		SendVoltageSensor(0, lID, BatLevel, pDevice->floatValue, "Voltage");
	}
```
to

```
	else if (pDevice->devType == ZDTYPE_SENSOR_VOLTAGE)
	{
		lID = (lID & 0xFFFFFF00) | pDevice->orgInstanceID;
		SendVoltageSensor(0, lID, BatLevel, pDevice->floatValue, "Voltage");
	}
```

**Comment by robal** [comment]
Brilliant. It created two voltage sensors in domoticz:
![image](https://user-images.githubusercontent.com/5574519/114269159-1a2f1180-99fd-11eb-88ae-7ad522fa7360.png)
and they both report voltage independently and correctly.
Many thanks @gizmocuz

**Comment by robal** [comment]
Actually, playing with the device some more revealed a similar bug with "Home Security" instances.
When inputs are configured as NO/NC alarm inputs, the alarm notifications should arrive via two instances of "Home Security" device.
It seems to be behaving similarly to voltage sensor inputs.
Alarm notification from both inputs arrive into a single device in domoticz:
![image](https://user-images.githubusercontent.com/5574519/114271018-4b144400-9a07-11eb-9cc3-7b4c514b0351.png)
There's only one device:
![image](https://user-images.githubusercontent.com/5574519/114271037-641cf500-9a07-11eb-8c64-ca1e5253022d.png)
Log shows that alarm comes from Instance 2. but the update still goes to 'Instance 1' domoticz device:
```
2021-04-10 13:41:50.641 Status: OpenZWave: Alarm received (Instance 2: Home Security: Clear), NodeID: 35 (0x23)
2021-04-10 13:41:52.476 Aeon Z-Stick 2E: Light/Switch (Instance 1: Switch)
2021-04-10 13:41:52.477 Python: Changed: ID: 1549 Name: Instance 1: Switch, Type: 244, subType: 73, switchType: 0, s_value: 255, n_value: 1, n_value_string: On, last_update_string: 2021-04-10 13:41:52
2021-04-10 13:41:52.477 Python: Number of user_variables: 0
2021-04-10 13:41:52.524 Aeon Z-Stick 2E: General/Alarm (Alarm Type: Instance 1: Home Security 7 (0x07))
2021-04-10 13:41:52.525 Python: Changed: ID: 1555 Name: Alarm Type: Instance 1: Home Security 7 (0x07), Type: 243, subType: 32, switchType: 0, s_value: Intrusion at Unknown Location, n_value: 2, n_value_string: Intrusion at Unknown Location, last_update_string: 2021-04-10 13:41:52 
```

**Comment by gizmocuz** [comment]
Great the voltage is solved...

Could you change the this code

```
	else if (pDevice->devType == ZDTYPE_ALARM)
	{
		_tGeneralDevice gDevice;
		gDevice.subtype = sTypeZWaveAlarm;
		gDevice.id = pDevice->Alarm_Type;
		gDevice.intval1 = lID;
		gDevice.intval2 = pDevice->intvalue;
		char szTmp[100];
		sprintf(szTmp, "Alarm Type: %s %d(0x%02X)", pDevice->label.c_str(), pDevice->Alarm_Type, pDevice->Alarm_Type);
		sDecodeRXMessage(this, (const unsigned char *)&gDevice, szTmp, BatLevel, nullptr);
	}

```
to

```
	else if (pDevice->devType == ZDTYPE_ALARM)
	{
		lID = (lID & 0xFFFFFF00) | pDevice->orgInstanceID;
		_tGeneralDevice gDevice;
		gDevice.subtype = sTypeZWaveAlarm;
		gDevice.id = pDevice->Alarm_Type;
		gDevice.intval1 = lID;
		gDevice.intval2 = pDevice->intvalue;
		char szTmp[100];
		sprintf(szTmp, "Alarm Type: %s %d(0x%02X)", pDevice->label.c_str(), pDevice->Alarm_Type, pDevice->Alarm_Type);
		sDecodeRXMessage(this, (const unsigned char *)&gDevice, szTmp, BatLevel, nullptr);
	}

```

I find this change a bit of high risk to change

But I assume you are going to use the switches (Instance 1: Switch and Instance 2: Switch) for this sensor ?

**Comment by robal** [comment]
I'll give it a try and report. Please be aware that FGBS-222 has two sets in SWITCH instances. One for controlling output relays, and one for showing state of inputs (button mode or alarm mode).
It can be confusing because Fibaro made it so inputs are tied to outputs (controlling input, changes the state of corresponding output).
To make it even more complicated this behaviour can be disabled using custom commands, but this is outside the scope of this issue.
![image](https://user-images.githubusercontent.com/5574519/114401673-0e795180-9b9b-11eb-8597-341336002842.png)
Ideally, Domoticz should create 2 voltage devices for inputs, 2 switch/alarm devices for inputs, and 2 switch devices for outputs.

**Comment by robal** [comment]
I've tried your code change, but I still get:
```
2021-04-12 15:42:20.440 Aeon Z-Stick 2E: General/Alarm (Alarm Type: Instance 1: Home Security 7 (0x07))
2021-04-12 15:42:20.441 Python: Changed: ID: 1555 Name: Alarm Type: Instance 1: Home Security 7 (0x07), Type: 243, subType: 32, switchType: 0, s_value: Intrusion at Unknown Location, n_value: 2, n_value_string: Intrusion at Unknown Location, last_update_string: 2021-04-12 15:42:20
2021-04-12 15:42:20.441 Python: Number of user_variables: 0
2021-04-12 15:42:20.441 Aeon Z-Stick 2E: Light/Switch (Instance 1: Home Security)
2021-04-12 15:42:20.442 Python: Changed: ID: 1552 Name: Instance 1: Home Security, Type: 244, subType: 73, switchType: 0, s_value: 255, n_value: 1, n_value_string: On, last_update_string: 2021-04-12 15:42:20
2021-04-12 15:42:20.442 Python: Number of user_variables: 0
2021-04-12 15:42:20.439 Status: OpenZWave: Alarm received (Instance 2: Home Security: Intrusion at Unknown Location), NodeID: 35 (0x23) 
```
I'm not sure if I'm compiling it right...  Or something else is weird. The code doesn't seem even to enter
``
else if (pDevice->devType == ZDTYPE_ALARM)
``
block..
I've tried modifying the ```sprintf(szTmp, "Alarm Type: ``` to make it print more, but my change doesn't affect the log output.

Am I doing a rookie mistake ?
I re-run ```make``` after modifications, and it rebuilds ZWavaBase.o and relinks the executable. It looks OK to me.

**Comment by gizmocuz** [comment]
You could try adding a log line with

Log(LOG_STATUS, "ZWave: This is a log message");

**Comment by gizmocuz** [comment]
I checked the code, the alarm sensor is actually send here

OpenZWave.cpp, ~line 3009

```
				if ((vOrgIndex > ValueID_Index_Alarm::Type_Start) && (vOrgIndex < ValueID_Index_Alarm::Type_Event_Param_Previous_Event))
				{
					char szTmp[100];
					sprintf(szTmp, "Alarm Type: %s %d (0x%02X)", vLabel.c_str(), vOrgIndex, vOrgIndex);
					SendZWaveAlarmSensor(pDevice->nodeID, pDevice->instanceID, pDevice->batValue, (uint8_t)vOrgIndex, intListValue, szListValue, szTmp);
				}

As this function is called only here, you could try modifying it and supply the OrgIndex and OrgInstance, and in SendZWaveAlarmSensor use these to construct a ID

But as you can also get the status as a switch (if you configure it correctly) you should now be able to use your node right ?

I don't mind changing ID's of sensors, but not before we made a new stable release as this cause existing users to get a new ID as well

```

**Comment by robal** [comment]
Thanks. I'll play around with the code.
At the moment alarm inputs are not usable (even via switch device), because there's only one instance:
````
2021-04-12 15:42:20.441 Aeon Z-Stick 2E: Light/Switch (Instance 1: Home Security)
2021-04-12 15:42:20.442 Python: Changed: ID: 1552 Name: Instance 1: Home Security, Type: 244, subType: 73, switchType: 0, s_value: 255, n_value: 1, n_value_string: On, last_update_string: 2021-04-12 15:42:20
````
Both alarms coming from Instance 1 and Instance 2 trigger change only of Instance 1 of General/Alarm and Light/Switch in domoticz.
In ```OpenZWave.cpp, ~line 3009``` instances are differentiated correctly. In ```ZWaveBase.cpp``` they're not.
I'll see if I can get the ID to pass correctly.

**Comment by gizmocuz** [comment]
You should be able to get the input status of both switches

**Comment by robal** [comment]
I can get the status of (and control) **output** relays (as two ```Light/Switch``` devices), without code changes.
On a factory-configured FGBS-222 (where input state is tied to output state), this means I can indirectly read input status too (via reading output status)

On my unit (which is configured to untie output state from input state), reading inputs' status is not possible yet.
Inputs present themselves as a pair of instances of ```alarm``` , ```light/switch```, and ```voltage``` devices.

Your original code fix helped separate instances of ```voltage```, so I can read them independently.
```Light/Switch``` and ```Alarm``` device instances are still merged into one in Domoticz.

I'm getting the hang of those IDs now... I come back with my findings soon.
I've tried adding ```vOrgInstance``` to ```instanceID``` to get a unique deviceID and got the ```Alarm``` devices split into 2 instances correctly now.
I'll see i I can do similar thing to ```Light/Switch``` input device.

**Comment by gizmocuz** [comment]
So when you configure your node correctly like (as default) you can use the switches ?

**Comment by robal** [comment]
Yes, the output relays work as expected with Domoticz.

**Comment by robal** [comment]
```Alarm``` devices are now OK.
```Light/Switch``` devices are merging, here:
````
2021-04-13 12:23:13.803 Status: SendSwitchIfNotExists: Device '35.instance.2.index.7.commandClasses.113' (Instance 2: Home Security) with DeviceID '00002335' matches '35.instance.1.index.7.commandClasses.113' (Instance 1: Home Security). Domoticz will use the Dimmer (and hide the Switch).
````
So it's merging ```35.instance.2.index.7.commandClasses.113``` with ```135.instance.1.index.7.commandClasses.113```
I'm not sure how to stop it.
This is ZWaveBase.cpp @ line 243

**Comment by gizmocuz** [comment]
I don't have time for this at the moment, and first a new stable has to be release.
Anyway, once you configure your node correctly you should be able to use it... I do... and it's working fine

**Comment by robal** [comment]
No worries. Thanks for your help on this !
I think only part of FGBS-222 functionality works correctly, but don't worry about it for now.
Anyway, I'll keep investigating and will suggest changes after the stable release.

**Comment by gizmocuz** [comment]
I am just curious what part does not work for you ? I get updates to the switches when the input contacts are closed/opened

**Comment by robal** [comment]
Those are actually output state updates you're looking at.
I agree, for most users (not using voltage sensors) it will be enough.

Inputs endpoints also exist in this device but are not correctly understood by Domoticz at the moment.
You can see input states by looking at outputs because they're tied together (FGBS-222 will change output state when input state changes)

Once you start looking at inputs themselves it becomes tricky in Domoticz.
When using inputs as analogue inputs, you have to look at them directly (as voltage sensors).
You've already solved the problem of ```Voltage``` inputs with the ```lID``` trick, and they are correctly visible after code change.

A more advanced scenario happens when you configure FGBS-222 to decouple inputs from outputs and use them separately.
Then, to monitor inputs, you have to look at input endpoints (Alarm / Switch devices in Domoticz), because changes to their state won't be reflected in outputs (which can be controlled separately).
These are not correctly visible in Domoticz yet (they are, but both instances merged into one)
An example of user facing this problem (also includes details in how to separate input/output): [https://www.domoticz.com/forum/viewtopic.php?p=267311#p267311](url)

**Comment by waltervl** [comment]
As OpenZwave is deprecated perhaps try ZwaveJS2MQTT, see wiki https://www.domoticz.com/wiki/ZwaveJS2MQTT .
 I close this issue. If there are issues in ZwaveJS2MQTT regarding this topic please create a new issue.
