### ISSUE TITLE
Domoticz doesn't start after ubuntu update to 22.04 (Due to OpenSSL3)

### ISSUE THREAD

**Issue by StKob** [domoticz/domoticz#5233]
Since 22.04LTS ubuntu switches to newer libssl which causes domoticz startup failure.  
`error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by JRB202** [comment]
Same problem.

How can we fix this problem ?

**Comment by JRB202** [comment]
openssl version        gives :
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

and : ls /usr/lib/x86_64-linux-gnu | grep libssl

libssl3.so
libssl.a
libssl.so
libssl.so.3

**Comment by JRB202** [comment]
For information, I found the way to install domoticz on Ubuntu 22.04 :

The option -DUSE_OPENSSL_STATIC="NO"  is the way to suppress the problem :

git clone https://github.com/domoticz/domoticz.git domoticz
cd domoticz
git pull 
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO" 
make

To test :
cd domoticz 
sudo ./domoticz -www 8080 -sslwww 443

**Comment by kiddigital** [comment]
Ubuntu 22.04LTS now comes with OpenSSL3 and does not have OpenSSL1 anymore.

See https://discourse.ubuntu.com/t/openssl-3-0-transition-plans/24453

One option is to also install the 'old' OpenSSL1 on your system.
You can download it from: http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb
(or the appropriate version for your system)
and install it via `sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb`

The Domoticz buildpipeline has to be updated to make use of OpenSSL3. The current (Beta) builds depend on OpenSSL1.

**Comment by gizmocuz** [comment]
Can this issue be closed? I think this is solved?

**Comment by JRB202** [comment]
Hi,

Thanks for update 

The Domoticz curl based installation script still fails with Ubuntu 22.04.

The only way is to recompile Domoticz 
but the automatic upgrade will not work.

Best regards

Jean-Regis BOULET

**Comment by CyrilB1531** [comment]
Hello,

I can see while compiling Domoticz that MD5_Init, MD5_Update and MD5_Final are deprecated in OpenSSL 3.0

Kind regards,
Cyril

**Comment by kiddigital** [comment]
Maybe update the MD5 function to higher level functions

See [here](https://stackoverflow.com/questions/69806220/advice-needed-for-migration-of-low-level-openssl-api-to-high-level-openssl-apis) for example.

**Comment by CyrilB1531** [comment]
There are 2 files to change: XiaomiGateway.cpp and main/Helper.cpp, I've tried to fix this but I haven't got Xiaomi devices to test modifications

**Comment by StKob** [comment]
using ./updatebeta doesn't resolve issue. libssl1.1 is still needed.

**Comment by CyrilB1531** [comment]
Until the build is done on Ubuntu 20.4 with libssl1.1 I think, we will have this problem... I will check again

**Comment by grogniakss** [comment]
It works by installing the old libssl. 
Here you have the link to :

http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

install it via **sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb**

reboot. Thanks to [kiddigital](https://github.com/kiddigital) for the idea.

**Comment by gizmocuz** [comment]
This is a very old thread. Anyway, please use the docker

**Comment by Spyky** [comment]
Du delivery problems of Raspberry i bought a odroid.
Pfff.. diffucult to get it working.
Now i run to this problem and tried
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

Then i get the message that it is not compatible with my version ..arm64.

Is there already another sollution or send the odroid back and buy a rasp :)

**Comment by gizmocuz** [comment]
Actually, I use odroids for quite some time and it is extreme easy!
I use armbian (of course) and installation is a breeze

After this, I use the system tool to install docker-compose
when docker compose is installed, I install the domoticz docker (docker-compose file)
up and running in no time, and does not depend on your system and openssl version

**Comment by Spyky** [comment]
> Actually, I use odroids for quite some time and it is extreme easy! I use armbian (of course) and installation is a breeze
> 
> After this, I use the system tool to install docker-compose when docker compose is installed, I install the domoticz docker (docker-compose file) up and running in no time, and does not depend on your system and openssl version

Thnks for the quick response.
Is there a manual to do it the way you mentioned?
This is what you mean i think https://www.domoticz.com/wiki/Docker
Will try that.

**Comment by gizmocuz** [comment]
@Spyky , I don't know this wiki page

First install Armbian on your system if you have not already done so

then use the armbian-config tool to configure your system and install docker

`sudo armbian-config`

(choose softy/software, and install docker)

Might take some time, so leave it alone for 5 minutes

Now Docker is installed and can be checked by running

`docker version`

Next install docker-compose with

```
sudo apt update
sudo apt-get install docker-compose-plugin
```

Next follow the instructions for setting up Domoticz with **docker-compose** here (creating a docker-compose.yml file)

https://hub.docker.com/r/domoticz/domoticz

**Comment by Spyky** [comment]
> @Spyky , I don't know this wiki page
> 
> First install Armbian on your system if you have not already done so
> 
> then use the armbian-config tool to configure your system and install docker
> 
> `sudo armbian-config`
> 
> (choose softy/software, and install docker)
> 
> Might take some time, so leave it alone for 5 minutes
> 
> Now Docker is installed and can be checked by running
> 
> `docker version`
> 
> Next install docker-compose with
> 
> ```
> sudo apt update
> sudo apt-get install docker-compose-plugin
> ```
> 
> Next follow the instructions for setting up Domoticz with **docker-compose** here (creating a docker-compose.yml file)
> 
> https://hub.docker.com/r/domoticz/domoticz

Top, thnks. Will try this.

**Comment by taohansens** [comment]
I have this error too, and i installed the lib in my server (Ubuntu 22.04 x64) with link and works fine:
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
`sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb`

**Comment by MichaIng** [comment]
I think as long as there is no way to dynamically use `libssl3` or `libssl1.1` depending on which one is present, there is no way than providing two builds, one for older OS versions (until Debian Bullseye and Ubuntu Focal) and one for newer ones (from Debian Bookworm and Ubuntu Jammy). Would this be feasible?

**Comment by gizmocuz** [comment]
Well that's not easily done and possible.

Sollution: Use the Docker Compose version of Domoticz and all these issues are gone

**Comment by MichaIng** [comment]
Of course, but a container engine is not always possible, reasonable or wanted in all cases. But of course one needs to accept or work around the limitations of the used distro (version) when installing a bare metal instance.

Is there a plan when new Domoticz binaries will be compiled against libssl3?

**Comment by gizmocuz** [comment]
This is one of the reasons docker is great!
Performance is not an issue.

As mentioned above, you can also compile Domoticz yourself, doing it sometimes multiple times a day myself

docker compose is great... see no reason why this would not work in all your cases? Please enlighten me....

**Comment by MichaIng** [comment]
I do not want to start a discussion about Docker or container engines here. It is great for several use cases, but not an option in our case for several reasons. Using it for running software with outdated cryptography libraries is nice as a short-term workaround, but probably the opposite of what I would use Docker for 🙂.

**Comment by gizmocuz** [comment]
OpenSSL 1.1 is safe what are you talking about? Specially what we use of it.

Edit: Besides, you are running your docker containers in a highly up to date system 😎

Anyway, what do you think when we start linking against another version of the library?
For example, everyone using buster/bullseye will have issues as it is running OpenSSL 1.1.1
It's installed with bookworm

The code base is ready for it for quite some time, and when compiling yourself on a system having OpenSSL 3.0 it will use this.

As the docker images are using the install packages directly, this is using Debian bullseye (slim)
This means everything needs to be upgraded.

Currently Raspbian is still bullseye, and a mayor of users is using this.

We migrated when Raspbian was using OpenSSL 1.1

**Comment by MichaIng** [comment]
> OpenSSL 1.1 is safe what are you talking about? Specially what we use of it.

Yes you are right. I meant the principle, but it does not apply well here.

> For example, everyone using buster/bullseye will have issues as it is running OpenSSL 1.1.1

This is why I was suggesting two builds, if applicable for your release pipelines. With a single build, I agree that it overall serves users better when keep linking against OpenSSL 1.1 for now.

> We migrated when Raspbian was using OpenSSL 1.1

Okay, good to know. We'll switch to own builds. Will be needed anyway as well after your builds use libssl3, to maintain latest Domoticz on Buster/Bullseye for our users, where they cannot or do not want to upgrade Debian itself.

**Comment by Dylantje** [comment]
Hope there is a option.. for install libssl1.1

Drive me cray.

 

I run:


  ___      _           _     _   _   _ ____
 / _ \  __| |_ __ ___ (_) __| | | \ | |___ \
| | | |/ _` | '__/ _ \| |/ _` | |  \| | __) |
| |_| | (_| | | | (_) | | (_| | | |\  |/ __/
 \___/ \__,_|_|  \___/|_|\__,_| |_| \_|_____|

Welcome to Armbian 23.05.1 Bookworm with Linux 6.1.30-meson64

System load:   2%               Up time:       31 min
Memory usage:  9% of 3.69G      IP:            192.168.5.70
CPU temp:      34°C             Usage of /:    9% of 57G
RX today:      499.3 MiB

Last login: Tue Jul 18 01:39:33 2023 from 192.168.5.101
 

Fow my Domoticz, in need, libssl1.1

 

Still get an error when run: 

pi@Domoticz:~$ cd domoticz
pi@Domoticz:~/domoticz$ ./domoticz
./domoticz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
pi@Domoticz:~/domoticz$
 

Where i google and try to find solutions.. No option to install libssl1.1 on my ondroid. [ also not with jammy ]

 
Or is there a option to update libsssl to newer version in Domoticz.
Will not run docker for this. problem.
 

Help please......

 

THANKS!!!

**Comment by PistoleroB57** [comment]
Hi,
The current link to the library is now (at the time of writing this) :
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb

**Comment by anno006** [comment]
Docker is not installing with the commands
sudo apt-get update && sudo apt-get upgrade

curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh

sudo usermod -aG docker ${USER}

sudo systemctl enable docker

sudo reboot

on https://www.domoticz.com/wiki/Docker

So it is inpossible to use domoticz on the newer ubuntu versions. 

I have no other choise than to use a olther version of if even this won't work copy a older vm machine with a working domoticz install.

it is at least wierd that u don't update the core componends for domoticz.

update: within 3 minutes installing ubuntu server 20.04.5 and installing domoticz, it works, without a problem. Meby it is time to look at home assistant after more than 10 years domoticz?!

**Comment by MichaIng** [comment]
The official Docker install instructions should work: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

Alternatively, the little older version provided by Ubuntu itself should work fine as well:
```sh
apt install docker.io
```

**Comment by gizmocuz** [comment]
@anno006 

Yes these instructions are also working on the latest Ubuntu, using it myself on multiple systems

Sure, feel free to switch your home automation system, specially because we mentioned three good solutions

- stay on a system using OpenSSL 1
- Use our docker compose version
- Just compile domoticz yourself

And how will you install HASS? Yes probably via docker compose indeed!

We have a very detailed wiki page about how to compile domoticz yourself
Should not take that long, and for updates even shorter

As it is probably safer in your case to stay with the stables, you might not need to compile that frequent

This is also a OSS project and we don’t get paid. But we want to help as much as possible to an extend

It might take a while until we can support both version 1 and 3 as we need to setup another build environment/system/step for this
So you best bet (and quickest) is to just compile yourself

**Comment by MichaIng** [comment]
Issue solved with the latest release/builds, which were compiled against libssl3.

EDIT: Ah, this is true for the builds here: https://github.com/domoticz/domoticz/releases/tag/2024.1
But the ones provided [here](https://www.domoticz.com/downloads/) are still built against libssl1.1. @gizmocuz is it intended that those differ? I mean it is basically the dual-builds solution I suggested before, but since they are provided via different platforms/servers without any reference to each other, it does not look like it is intended or will remain like this.

EDIT2: Okay, even more confusing: The `x86_64` builds from GitHub are compiled against libssl3, but the ARM ones are both compiled against libssl1.1 🤔. Is the build system in the middle of a transition?

**Comment by MichaIng** [comment]
Latest x86_64 build on GitHub depends on libssl1.1 again (as all others). Bookworm has been released since nearly 2 years and Ubuntu Jammy since 3 years. Both latest supported distro versions (Debian Bullseye and Ubuntu Focal) are EOL already. Switching to to libssl3 builds is overdue, if there shall be any use of the provided binaries at all.

**Comment by gizmocuz** [comment]
I know, problem is that there are many users using 1.1 still. I choose to make one more stable with 1.1, the beta version will switch to v3 soon.
It is bad design from libssl to not backward compatible and naming their libraries differently
Anyway, on our forum this is discussed and also the sollution

**Comment by MichaIng** [comment]
Sounds good.

Yeah I agree it would have been nice to have some compatibility SHIM or the ability to install both versions concurrently for one distro version at least (they have no file overlap).

Two Domoticz binaries/archives would be great for such cases, to support Bullseye/Focal and older as well as Bookworm/Jammy and newer. But to be honest, the `makerelease` script seems to make it very easy to build own ones. It is just that the libssl3 incompatible ones are so prominently linked at https://www.domoticz.com/downloads/ as well.

**Comment by gizmocuz** [comment]
I changed the updater scripts and now OpenSSL version 3 is mandatory
So everyone that updates now to the current beta will be safe
But I bet we will get lots of user complaints that Domoticz won't start anymore
At least, when there is OpenSSL4 or higher, that won't be an issue anymore

**Comment by MichaIng** [comment]
That is clever. So at least if people updates to the current beta/next release, they won't run into an incompatible version. But it they skip the upcoming version, they will, right?

For our case, it is indeed less of an issue, since we provide a pretty functional Debian Bullseye => Bookworm distro upgrade script, and will promote that anyway more actively to our users once Trixie has been released this summer.

What would be nice is a way to disable the internal update checker and updater via compile time argument. At least I did not see it. `-noupdates` can be passed, but can be still enabled and is then overridden by the web UI settings. If we provide own packages (and updates) via our APT repo, to avoid possible back- and forth upgrades between incompatible versions, we'd need a way to disable the internal update functionality completely.

**Comment by gizmocuz** [comment]
it is intended that -noupdates should not make the update visible... let me debug this. I just added a check to disable this when it detects it is running in a docker enviroment

**Comment by MichaIng** [comment]
Yeah sorry I just realized that we override it via [`domoticz.conf`](https://github.com/domoticz/domoticz/blob/development/scripts/domoticz.conf#L83) where it can be disabled. The (existence of the) config file overrides other cmd arguments, at least this one. Okay that works well enough. But would still be nice to prevent it via compile time option completely, so admins cannot enable it for these builds via config file either.

**Comment by gizmocuz** [comment]
Pfview 🥵😰😅 I thought it was broke...

Yes, that could be an option.... 

Added in latest commit, is it possible to test?

option(DISABLE_UPDATER "Disable updater functionality" NO)

**Comment by gizmocuz** [comment]
Could you point me to your Debian Bullseye => Bookworm update script?

I used 

`https://www.cyberciti.biz/faq/update-upgrade-debian-11-to-debian-12-bookworm/`

Which works pretty well!

**Comment by MichaIng** [comment]
That one is for our DietPi OS: https://github.com/MichaIng/DietPi/blob/dev/.meta/dietpi-bookworm-upgrade
I always wanted to create a non-DietPi/generic Debian variant of it. It essentially does the same as the nixCraft guide + some generic (Debian) + some DietPi-specific migration steps.

I see nixCraft covers `non-free-firmware` already. For WiFi systems, there is another migration for the CRDA feature needed, Unbound  to work as recursive DNS resolver the `dns-root-data` package is needed (degraded from dependency to recommendation in Debian), a small Redis server config adjustment, and it covers Python, PHP and PostgreSQL migration. Some stuff we collected from user reports over the time.

But it is easier to decide which step can be safely done by a script and which should be better manually done by the admin, when known that software was installed with our related scripts in a managed way. E.g. migrating the PostgreSQL database when knowing for sure it is v13 package from the Debian Bullseye repository is okay, but otherwise it could be any PostgreSQL version compiled or pulled from elsewhere and the migration could cause havoc.

**Comment by gizmocuz** [comment]
Whoops, I just updated my DietPi system yesterday and which I found your guide earlier 😁
Going to perform the additional steps in the scripts!

**Comment by MichaIng** [comment]
I finally found the time to implement Debian package builds our end. First of all, with `development` branch, despite passing `-DDISABLE_UPDATER=1` to `cmake`, the update checker pops up:

<img width="359" height="116" alt="Image" src="https://github.com/user-attachments/assets/8a069a18-108b-4849-a255-1029bc190834" />

`updates=no` in the config file works.

Checking the code: https://github.com/domoticz/domoticz/blob/development/main/domoticz.cpp#L793-L797

Is the syntax probably adding it to the `AreWeRunningInDocker()` condition? Maybe that would work?
```cpp
#ifdef DISABLE_UPDATER
	g_bUseUpdater = false;
#else
	if (AreWeRunningInDocker())
		g_bUseUpdater = false;
#endif
```

And two questions regarding the build:

```
-- WITH_DLT = OFF
-- Could NOT find cJSON (missing: CJSON_INCLUDE_DIR CJSON_LIBRARY)
-- Optional dependency cJSON not found. Some features will be disabled.
```
As far as I understood from other issues, cJSON is an optional dependency of Mosquitto, but not needed for Domoticz's embedded Mosquitto build?

```
-- ==== OpenZWave not found, support disabled!
```
As far as I understood, OpenZWave is not supported anymore by Domoticz. Would it make sense to remove the related option and check from [`CMakeLists.txt`](https://github.com/domoticz/domoticz/blob/development/CMakeLists.txt#L742-L773)?

**Comment by gizmocuz** [comment]
Parsing -DDISABLE_UPDATER should work... You should not need =1
I just made a commit to make the code a bit more readable (#ifdef DISABLE_UPDATER)

OpenZWave is included and functioning in Domoticz again since quite some time... I would suggest to leave this in... 
In the end, everyone should switch to ZWaveJS-UI, but some users are having issues installing the application, even with docker compose

CJSON is not referred anywhere in the Domoticz project, also not inside the CMakeList.txt file. I guess this error is coming from a external library. It could indeed be mosquitto
Same goes for WITH_DLT ... this is not used in the Domoticz project

**Comment by MichaIng** [comment]
> Parsing -DDISABLE_UPDATER should work... You should not need =1
I just made a commit to make the code a bit more readable (#ifdef DISABLE_UPDATER)

Okay, I'll retry without `=1`.
EDIT:
```
cmake -B ../build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/domoticz_aarch64/opt/domoticz -DDISABLE_UPDATER
CMake Error: Parse error in command line argument: DISABLE_UPDATER
 Should be: VAR:type=value
```
So an explicit `=1/y/yes/true/on` is needed.

> OpenZWave is included and functioning in Domoticz again since quite some time... I would suggest to leave this in...
In the end, everyone should switch to ZWaveJS-UI, but some users are having issues installing the application, even with docker compose

Ah good to know, then I'll add it back in. IIRC when I tried first, I was running into another error, but let's see. In the [Docker image](https://github.com/domoticz/domoticz/blob/development/build/Dockerfile) it is currently missing, isn't it?

**Comment by gizmocuz** [comment]
Could you try with ON ?

I tested with Visual Studio (preprocessor setting), it just needs this to be added in there.

No, in the docker image OpenZWave is also enabled (as it us using the binary archive from the AMD 32/64 and ARM64 builds)

**Comment by MichaIng** [comment]
> Could you try with ON ?

Does not work either 🤔. This is how I called it:
```sh
cmake -B ../build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/tmp/domoticz_x86_64/opt/domoticz" -DDISABLE_UPDATER=ON
```
with latest `development´ commit + #6366.

I'll add some debug code to track this down locally.

**Comment by MichaIng** [comment]
Okay, `IF(DISABLE_UPDATER)` returns true in `CMakeLists.txt`, but `#ifdef DISABLE_UPDATER` returns false in `domoticz.cpp`. It guess this makes sense as I do not pass this as environment variable, but as cmake option, and it is not turned into a variable there either.

And now it makes sense, I confused `cmake -DKEY=value` options (which require a value) and `g++ -DMACRO` macros, which do not require a value. So the missing link here is that passing the cmake option does not create the compiler macro. And in Visual Studio you added it as compiler macro directly, not as cmake option.

I'll open a PR to create the macro from the option: #6368

**Comment by gizmocuz** [comment]
Thanks for the PR, it's merged!
