### ISSUE TITLE
Graph/Log pop up disappear too fast

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#5497]
Like in the video attached
Safari on macOS
https://user-images.githubusercontent.com/22882393/209439547-ae72a356-6c79-4ef1-81f8-2bd60ac8f5bf.mov

On chrome (macOS) this doesn't happen but clicking on some device on Show Graph a blank page appears, instead clicking log graph appears

https://user-images.githubusercontent.com/22882393/209439728-209c00ad-65dd-495d-ae9b-cefedfab97c9.mov

**Comment by gizmocuz** [comment]
Seems to happen with percentage devices only? I have a look at this

**Comment by acaonweb** [comment]
if I click on graph to  real hardware device, for example battery exposed from a Zigbee device trought zigbe2mqtt, graph page appears.
In a dummy lux device, where is not a percentage but a value, from dashboard, the log page is blank but from the device the page Is ok

**Comment by gizmocuz** [comment]
@acaonweb , not sure what you are talking about. You are on the latest beta correct and does this solves your initial issue on the floorplan?
You now have a issue on the dashboard?

**Comment by acaonweb** [comment]
Well I've still two issues:
1) the pop up windows disappears immediately on Safari, so it's impossible for example open log page for a device from the dashboard.
2) now for a percentage device (I have battery device from an zigbee2mqtt hardware) from dashboard I can open log page BUT for a dummy device like LUX, the graph isn't opened from dashboard 
I attach a video to show you better

https://user-images.githubusercontent.com/22882393/210326212-290fee62-5add-4056-ab10-fe147fbde60f.mov

**Comment by acaonweb** [comment]
now it's ok about graph.. popup still disappearing too fast on Safari

**Comment by gizmocuz** [comment]
What Domoticz version you have installed? (Latest beta ?)

**Comment by acaonweb** [comment]
Version: 2022.2 (build 14958)
Build Hash: 461faff2b
Compile Date: 2023-01-13 15:16:13
dzVents Version: 3.1.8

**Comment by gizmocuz** [comment]
Thanks!
Found one issue, the log is calling 'ShowLuxLog' , but this function does not exists and it should call a page like

http://<ip>:8080/#/Devices/<idx>/Log

This has been solved in beta 14963

Is the lux sensor that disappears immediately also of type lux/lux ? Or is it a custom sensor?

![image](https://user-images.githubusercontent.com/2265299/212550973-63fe8add-9189-4bdd-bf44-43cf72e62a84.png)

Do  you also have this issue when you use the Edge browser?

**Comment by acaonweb** [comment]
I have the disappearing stuffs on every device/sensor on the dashboard, and in Safari macOS
In safari iOS iPadOS it doesn't disappear but log isn't clickable

**Comment by acaonweb** [comment]
After 14963, graph issue remains for my lux device which is a dummy device, Lux type.

**Comment by gizmocuz** [comment]
After 14963 the log should be clickable and taken to the right log.
Tested with a dummy Lux device
Could you try the edge browser and see if the disappearing problem exists?

**Comment by acaonweb** [comment]
14963
Chrome: disappearing:NO log:NO
Edge: disappearing:NO log:NO
Safari macOS: disappearing:YES log:NO

**Comment by gizmocuz** [comment]
Okey, thats good to know
What macOS version are you running? (Ventura?) , I mean hope safari is running with it's latest version

I use Edge on all my devices, love the browser and I can work across all device with it
Sure it's no real solution....

**Comment by acaonweb** [comment]
I'm using last macOS Ventura 13.1
Disappearing is not a real problem indeed but maybe one day it will be resolved for the love of domoticz. 
I'm not a programmer and I can't help 
For the log, instead, I think it could be very useful kill the bug 😄

**Comment by gizmocuz** [comment]
Maybe the 'bug' is inside Safari and not Domoticz. Maybe you could ask them what seems wrong with either Safari or the widget

**Comment by acaonweb** [comment]
> Maybe the 'bug' is inside Safari and not Domoticz. Maybe you could ask them what seems wrong with either Safari or the widget

for fast disappearing of popup i agree, but log page isn't working on chrome too :)

**Comment by gizmocuz** [comment]
Did you clear your browser cache?

**Comment by acaonweb** [comment]
> Did you clear your browser cache?

yes I did
