### ISSUE TITLE
Thermostat in pilot app doesn't work

### ISSUE THREAD

**Issue by nielsbos38** [domoticz/domoticz#5840]
Good morning,

Since the last (beta) update, the thermostat no longer works in the Pilot or Domoticz app. Is there a solution for this?

Kind regards,
Niels Bos

**Comment by gizmocuz** [comment]
It does not work in the Domoticz web interface? What thermostat do you have?

**Comment by nielsbos38** [comment]
yes, it works in the web interface. They are standard dummy thermostats. in the domoticz or pilot app the option to adjust it is gone. You only see the set temperature, but you cannot change it.

**Comment by gizmocuz** [comment]
There have been some changes to the Setpoint devices to support other units then temperature.
Is it possible you can contact the author of the domoticz/pilot application?

**Comment by waltervl** [comment]
Created issue on Domoticz Android app https://github.com/domoticz/domoticz-android/issues/704

**Comment by waltervl** [comment]
Closing this issue as it should be fixed in the app.

**Comment by jguelim** [comment]
Can you reopen this issue? it is still not fixed I updated to the latest release and now I can not change a setpoint in the app it worked perfect in the old releases... i'm using the app since 2015 and never had this problem.

In the screenshot I market the place where the ZET button was.
![image](https://github.com/domoticz/domoticz/assets/155689870/6ed53f93-6824-4b84-828c-e0648bed0293)
And here in the screenshot you can see how it was before the update.
![image](https://github.com/domoticz/domoticz/assets/155689870/9b234157-e4e9-4391-9596-07baef1a8255)
I hope you can come with a solution soon we are using the app a lot in our house.

Greetings Jeroen

**Comment by waltervl** [comment]
@jguelim Sorry, this needs to be fixed in the android app. It has a separate repository. Better to react in the related app issue https://github.com/domoticz/domoticz-android/issues/704
