### ISSUE TITLE
Delete from graph only works 1 time, need refresh F5 to continue

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#6341]
2025.1 beta (and stable)
Using the Shift-Click action in day graph to delete a temperature or percentage (and probably more device types) measurement from the database only works the first time. If you need to delete another value you first have to refresh the device log/graph page manually with F5 before able to delete the second value.

The second time delete without refresh will give no error but the delete is not executed.
Tests executed on Windows and Android browser.

See also forum discussion https://forum.domoticz.com/viewtopic.php?p=326044

**Comment by gizmocuz** [comment]
Thanks for reporting!

Yep, found this out yesterday... the issue is in www/app/log/RefreshingChart.js, line 179

`self.$route.reload();`

This does not really refresh the page, we need to use

`window.location.reload();`

Solved in beta 16712

**Comment by waltervl** [comment]
I tested this beta but it does not seem to solve the issue.....
I will test it more this evening.

**Comment by gizmocuz** [comment]
Hope it's working, seems to work here (edge browser) (I tested deleting points in the short log, top graph)
Solution seems easy, maybe it is more complicated and we need to use self.$window.reload(); but $window is not provides and needs to be added

**Comment by waltervl** [comment]
Yes, it is working...
So thanks for fixing!
