### ISSUE TITLE
Update settings using an API request

### ISSUE THREAD

**Issue by averter** [domoticz/domoticz#6392]
**Describe the Issue**
Not actually a bug, just probably missing information from the documentation of the API. I want to update a setting in domoticz `CostEnergy` but am unable to and there is no information in the wiki or the forum :-(

**To Reproduce**
1. I've run the code 1 below to fetch settings. One of them is what I'm after: `CostEnergy` 
2. I've then asked DuckAI if there is a way to update settings and he suggested `setsettings` and the code 2 below which I've also run.
3. The result is  {'status': 'ERROR'}

**Expected behavior**
The setting CostEnergy to be updated in domoticz

**Screenshots**
N/A

**Additional context**
I need this to automatically update energy prices which are fetch from my energy supplier.

**Possible Implementation**
Code 1
````python
import requests
import pprint

# Configuration
DOMOTICZ_URL = 'http://192.168.26.12:8080/json.htm'

# Function to fetch settings information
def fetch_settings_info():
    response = requests.get(f"{DOMOTICZ_URL}?type=command&param=getsettings")
    if response.status_code == 200:
        data = response.json()
        return data
    else:
        print("Error fetching hardware info:", response.status_code)
        return None
    
# Main logic
settings_info = fetch_settings_info()
pprint.pprint(settings_info)
````
Code 2
````python
import requests
import pprint

# Configuration
DOMOTICZ_URL = 'http://192.168.26.12:8080/json.htm'

# Function to update settings
def update_settings(setting_name, new_value):
    update_url = f"{DOMOTICZ_URL}?type=command&param=setsettings&{setting_name}={new_value}"
    response = requests.get(update_url)
    if response.status_code == 200:
        data = response.json()
        if data['status'] == 'OK':
            return data
        else:
            print("Error in response:", data)
            return None
    else:
        print("Error updating settings:", response.status_code, response.text)
        return None

# Example usage
result = update_settings('CostEnergy', '0.2776')
pprint.pprint(result)
````

**Comment by gizmocuz** [comment]
You can't change this via an API call, you need to set this via the settings in GUI.
You also do not need to modify this. It is fixed
If you have a dynamic contract, and are a Dutch resident, you can add the Enever hardware.
If you are not, you can create your own python plugin and create a cost device for this, and configure via the setting to use this

**Comment by averter** [comment]
I'm not a Dutch resident (most users of Domoticz seem to be :-) ) and in my case I have a low/high tariff (low period is between 0:30AM and 5:30AM). The tariff is not fixed, in that every couple of months the energy supplier sends a notification that prices will rise or drop. I just don't want to have to bother about those price changes, and I'd rather fetch the prices from their API and update domoticz accordingly. I also have to track return energy prices, which I can export with my PV system.
Based on my understanding of the documentation and your message, dynamic pricing allows me to achieve the above for the consumption (not export) prices using the "Electricity price device"?

<img width="1203" height="744" alt="Image" src="https://github.com/user-attachments/assets/327fc25e-dca5-4948-a91a-08c759cf676b" />

  If so I have now created this virtual sensor

<img width="1179" height="234" alt="Image" src="https://github.com/user-attachments/assets/6e012450-4f4d-46f7-ba27-597687a1d4af" />

which is being updated at every minute by a python script based on the information from my energy supplier API. 
Questions:
- Am I right in assuming that there is no way to do the same for export (return prices)?
- The 1 minute update seems to be a requirement (based on [this post](https://forum.domoticz.com/viewtopic.php?p=322024)) but also to make sure that there's minimal cost discrepancy during the transitions from low/high or high/low periods?
- When you say that the values in that tab are "fixed" do you mean that they apply for all time (past and future of any manual change)? (I think that I've read that this is the case somewhere in the domoticz forums).

Thanks!

**Comment by waltervl** [comment]
The Custom sensor holding the current energy tariff should be updated min every 60 min or according your default sensor timeout setting.
https://wiki.domoticz.com/Application_Settings#%28Dynamic%29_Price_calculation

There is currently no return tariff unless you use the internal tariffs.

As soon as the internal tariffs change by you they are used for cost calculation. The old calculated cost calculations are not changed. The data in the database that has no cost calculation (so before you enabled cost calculation) are updated to the new tariffs .

**Comment by averter** [comment]
Thanks. I've kept updating the dummy device every minute and the script has been working great: there's been an increase of the high tariff now in beginning of October and it shows clearly in the time history.

<img width="1173" height="306" alt="Image" src="https://github.com/user-attachments/assets/5e9db094-6b98-429f-8245-2657edac5fb6" />

I see that there's lots of WHAT IF in this price calculation task. One more that I can think of is

1. suppose I update return prices via the internal tariffs
2. at that point in time, I assume that the T1 and T2 costs' values in the internal tariffs are used instead of the ones from the electricity price device
3. then as soon as the dummy device is updated in the following minute T1/T2 costs are updated again
Is the above correct? Basically, I am assuming that domoticz uses the cost prices of what has been updated most recently (device or internal tariff values in the settings menu). Thanks in advance for confirming and closing as this seems to be sorted.
