### ISSUE TITLE
Schedule (weekday) not working

### ISSUE THREAD

**Issue by red3333** [domoticz/domoticz#6452]
**Describe the Issue**
When using "Schedule (weekday)" planning for a device, the device is switched every second (instead of once a month).

**To Reproduce**

I want to schedule a OFF then ON (30min later) every 1st monday of month for a Fibaro (zwave) wallplug.
I edited the "planning", and set Type to "Monthly (weekday)", then day as "First" "Monday".
I set 2 entries:
Monthly (weekday), First Monday, 10:00, switch ON
Monthly (weekday), First Monday, 10:30, switch OFF

In the logs, I seed flooding every second in the form:
`
 2025-11-24 11:30:20.443 Status: Schedule item started! Name: Cave a vin, Type: Monthly (Weekday), DevID: 1126, Time: 2025-11-24 11:30:20

2025-11-24 11:30:21.444 Status: Schedule item started! Name: Cave a vin, Type: Monthly (Weekday), DevID: 1126, Time: 2025-11-24 11:30:21

2025-11-24 11:30:21.444 Status: Schedule item started! Name: Cave a vin, Type: Monthly (Weekday), DevID: 1126, Time: 2025-11-24 11:30:21

2025-11-24 11:30:22.445 Status: Schedule item started! Name: Cave a vin, Type: Monthly (Weekday), DevID: 1126, Time: 2025-11-24 11:30:22

2025-11-24 11:30:22.445 Status: Schedule item started! Name: Cave a vin, Type: Monthly (Weekday), DevID: 1126, Time: 2025-11-24 11:30:22 
`
At the same time, I hear the wallplug click ON, then OFF, then again ON in frenetic loop.

If I change the schedule to "Monthly" and day to "24", the behaviour is correct (one OFF at OFF configured time, then one ON at the ON configured time).

**Expected behavior**
The action should only happen once a month.

**Screenshots**

**Additional context**

Domoticz Version: 2025.2

Installation type: standalone application running on Debian Trixie virtual machine (ESXi, x86)

**Comment by gizmocuz** [comment]
Thank you for reporting. I guess the one implemented this many many years ago did not do some good testing.

I think I fixed in it in beta 16936

I also changed the Yearly (weekday) code.

Is it possible to test both? As far as I could test it seems to work....

**Comment by red3333** [comment]
Sad news: I tried with the 16936 beta, and it does not solve the problem.
The flood in logfile not longer happen, but actually, nothing happens at all.

I tried to generate an action on Monthly, 3rd tuesday  , then Monthly 4th tuesday, and Monthly last tuesday:
no entry in logfile
no effect on device

The Monthly, 25th works correctly, as before (entry in logfile and device switches).

**Comment by gizmocuz** [comment]
Sorry about that... The Yearly type should have worked, but on the Monthly (Weekday) I tested against the wrong time!
Fixed in beta 16952
